/**
 * v2.19.14 — MNEME CLI DREAMS (idle-time insight generation)
 *
 *   "When you sleep, your codebase doesn't. Mneme's daemon spawns 100
 *    plausible-but-unverified claims about your repo during idle hours
 *    (local Ollama, free). Each enters a CHRONOSTASIS-style witness loop;
 *    refutations file in overnight; by morning the crystallised survivors
 *    appear as a digest: 'while you slept, here are 5 facts I now know
 *    about your repo that I didn't know yesterday'.
 *
 *    No vendor will ship this because it costs compute + risks runaway
 *    cloud cost. Mneme runs it on YOUR machine via local-only inference;
 *    cost is amortised across hours nobody is using the machine. The CLI
 *    that learns about you while you sleep."
 *
 * Architecture (vendor-agnostic orchestrator):
 *   - `enqueueDreams({seeds})` — caller supplies N plausible claim strings
 *     (generated by their preferred local model). We HMAC-tag each one
 *     and add to the pending queue.
 *   - `recordDreamVerdict({dreamId, verdict, evidence?})` — caller (or
 *     CHRONOSTASIS in v2.19.5) reports the witness verdict per dream.
 *   - `morningDigest({since?})` — returns the night's crystallised dreams
 *     + refuted ones (for honest accounting) + still-pending count.
 *   - HMAC-chained ledger so the digest is tamper-evident.
 *
 * Honest scope:
 *   - We do NOT generate the dreams — caller does (Ollama, Claude, etc.).
 *   - We do NOT execute witness verdicts — caller does (Mneme INVERSE-LLM,
 *     CHRONOSTASIS, or any other verifier).
 *   - We provide: queue, dedup, verdict state machine, digest aggregation,
 *     chain integrity.
 */

import { createHmac, timingSafeEqual } from "node:crypto";

const PROTOCOL_VERSION = 1 as const;
const MAX_DREAMS_PER_NIGHT = 1000; // sanity cap

export type DreamStatus = "pending" | "verified" | "refuted" | "inconclusive";

export interface DreamRecord {
  v: typeof PROTOCOL_VERSION;
  id: string;
  claim: string;
  source: string; // e.g., "ollama:llama3:70b" or "claude:sonnet"
  status: DreamStatus;
  generatedAt: number;
  resolvedAt: number | null;
  evidence: string | null;
  /** Confidence reported by the witness, [0..1]. */
  confidence: number | null;
  prevSig: string | null;
  sig: string;
}

export interface DreamLedger {
  v: typeof PROTOCOL_VERSION;
  records: DreamRecord[];
}

function canon(v: unknown): string {
  if (v === null || typeof v !== "object") return JSON.stringify(v);
  if (Array.isArray(v)) return "[" + v.map(canon).join(",") + "]";
  const keys = Object.keys(v as Record<string, unknown>).sort();
  return "{" + keys.map((k) => JSON.stringify(k) + ":" + canon((v as Record<string, unknown>)[k])).join(",") + "}";
}

function defaultSecret(): string {
  return process.env["MNEME_DREAM_SECRET"] || `mneme-cli-dreams-v${PROTOCOL_VERSION}`;
}

function signRecord(body: Omit<DreamRecord, "sig">, secret: string): string {
  return createHmac("sha256", secret).update(canon(body)).digest("hex");
}

function safeEqHex(a: string, b: string): boolean {
  try { return timingSafeEqual(Buffer.from(a, "hex"), Buffer.from(b, "hex")); }
  catch { return false; }
}

function makeDreamId(claim: string, generatedAt: number): string {
  return "drm-" + createHmac("sha256", "mneme-dream-id")
    .update(`${claim}|${generatedAt}`)
    .digest("hex").slice(0, 14);
}

export function emptyDreamLedger(): DreamLedger {
  return { v: PROTOCOL_VERSION, records: [] };
}

export interface EnqueueInput {
  ledger: DreamLedger;
  seeds: Array<{ claim: string; source: string }>;
  nowMs?: number;
  secret?: string;
}

export interface EnqueueResult {
  ledger: DreamLedger;
  enqueued: number;
  duplicatesSkipped: number;
  rejectedAtCap: number;
}

/**
 * Add new dreams to the queue. Deduplicates by EXACT claim (case-sensitive)
 * across existing pending records. Hard cap MAX_DREAMS_PER_NIGHT prevents
 * runaway queues even if a generator misbehaves.
 */
export function enqueueDreams(input: EnqueueInput): EnqueueResult {
  const nowMs = input.nowMs ?? Date.now();
  const secret = input.secret ?? defaultSecret();
  const pendingClaims = new Set(
    input.ledger.records.filter((r) => r.status === "pending").map((r) => r.claim),
  );
  let added: DreamRecord[] = [];
  let duplicates = 0;
  let rejected = 0;
  const pendingCountBefore = pendingClaims.size;
  for (let i = 0; i < input.seeds.length; i++) {
    const seed = input.seeds[i]!;
    if (pendingClaims.has(seed.claim)) {
      duplicates++;
      continue;
    }
    if (pendingCountBefore + added.length >= MAX_DREAMS_PER_NIGHT) {
      rejected++;
      continue;
    }
    pendingClaims.add(seed.claim);
    const prevSig = added.length > 0
      ? added[added.length - 1]!.sig
      : (input.ledger.records[input.ledger.records.length - 1]?.sig ?? null);
    const body: Omit<DreamRecord, "sig"> = {
      v: PROTOCOL_VERSION,
      id: makeDreamId(seed.claim, nowMs + i),
      claim: seed.claim,
      source: seed.source,
      status: "pending",
      generatedAt: nowMs + i,
      resolvedAt: null,
      evidence: null,
      confidence: null,
      prevSig,
    };
    const sig = signRecord(body, secret);
    added.push({ ...body, sig });
  }
  return {
    ledger: { v: PROTOCOL_VERSION, records: [...input.ledger.records, ...added] },
    enqueued: added.length,
    duplicatesSkipped: duplicates,
    rejectedAtCap: rejected,
  };
}

export interface VerdictInput {
  ledger: DreamLedger;
  dreamId: string;
  verdict: "verified" | "refuted" | "inconclusive";
  evidence?: string;
  confidence?: number;
  nowMs?: number;
  secret?: string;
}

/**
 * Record the witness verdict for a previously-enqueued dream. Pure update:
 * we DO NOT re-sign earlier records (their HMAC stays valid against their
 * own body). A new record appended captures the verdict — the chain remains
 * appendable and the dream's status is derived from the most-recent record
 * for its id.
 */
export function recordDreamVerdict(input: VerdictInput): { ledger: DreamLedger; ok: boolean; reason?: string } {
  const orig = input.ledger.records.slice().reverse().find((r) => r.id === input.dreamId);
  if (!orig) return { ledger: input.ledger, ok: false, reason: `dream id '${input.dreamId}' not found` };
  if (orig.status !== "pending") {
    return { ledger: input.ledger, ok: false, reason: `dream '${input.dreamId}' already resolved (status=${orig.status})` };
  }
  const nowMs = input.nowMs ?? Date.now();
  const prevSig = input.ledger.records[input.ledger.records.length - 1]!.sig;
  const body: Omit<DreamRecord, "sig"> = {
    v: PROTOCOL_VERSION,
    id: orig.id,
    claim: orig.claim,
    source: orig.source,
    status: input.verdict,
    generatedAt: orig.generatedAt,
    resolvedAt: nowMs,
    evidence: input.evidence ?? null,
    confidence: input.confidence ?? null,
    prevSig,
  };
  const sig = signRecord(body, input.secret ?? defaultSecret());
  return {
    ledger: { v: PROTOCOL_VERSION, records: [...input.ledger.records, { ...body, sig }] },
    ok: true,
  };
}

export interface MorningDigest {
  generatedAt: string;
  windowStartMs: number;
  totalDreamed: number;
  crystallised: DreamRecord[];
  refuted: DreamRecord[];
  inconclusive: DreamRecord[];
  stillPending: number;
  ratioCrystallised: number;
}

/**
 * Aggregate dreams generated since `since` into a morning digest.
 * Returns the LATEST record per dream id (so status reflects the verdict).
 */
export function morningDigest(opts: {
  ledger: DreamLedger;
  since?: number;
  nowMs?: number;
}): MorningDigest {
  const since = opts.since ?? 0;
  // Latest record per id (since the chain may have multiple updates).
  const byId = new Map<string, DreamRecord>();
  for (const r of opts.ledger.records) {
    if (r.generatedAt < since) continue;
    byId.set(r.id, r);
  }
  const all = Array.from(byId.values());
  const crystallised = all.filter((r) => r.status === "verified");
  const refuted = all.filter((r) => r.status === "refuted");
  const inconclusive = all.filter((r) => r.status === "inconclusive");
  const stillPending = all.filter((r) => r.status === "pending").length;
  const total = all.length;
  return {
    generatedAt: new Date(opts.nowMs ?? Date.now()).toISOString(),
    windowStartMs: since,
    totalDreamed: total,
    crystallised,
    refuted,
    inconclusive,
    stillPending,
    ratioCrystallised: total === 0 ? 0 : crystallised.length / total,
  };
}

/** Verify the HMAC chain of the dream ledger (prevSig + sig per record). */
export function verifyDreamLedger(ledger: DreamLedger, secret?: string): { ok: boolean; brokenAt?: number; reason?: string } {
  const sec = secret ?? defaultSecret();
  let prevSig: string | null = null;
  for (let i = 0; i < ledger.records.length; i++) {
    const r = ledger.records[i]!;
    const { sig, ...body } = r;
    if (body.prevSig !== prevSig) {
      return { ok: false, brokenAt: i, reason: `prevSig mismatch at step ${i}` };
    }
    if (!safeEqHex(signRecord(body, sec), sig)) {
      return { ok: false, brokenAt: i, reason: `HMAC mismatch at step ${i}` };
    }
    prevSig = sig;
  }
  return { ok: true };
}

export function listPendingDreams(ledger: DreamLedger): DreamRecord[] {
  const byId = new Map<string, DreamRecord>();
  for (const r of ledger.records) byId.set(r.id, r);
  return Array.from(byId.values()).filter((r) => r.status === "pending");
}

export function formatDigestLine(d: MorningDigest): string {
  return `🦠 DREAMS · ${d.crystallised.length} crystallised · ${d.refuted.length} refuted · ${d.stillPending} pending · ratio=${d.ratioCrystallised.toFixed(2)}`;
}
