/**
 * `mneme time-capsule` — Phase 7: handover artifact for new-hire onboarding.
 *
 * Strategic role: end of every quarter / sprint / year, generate a single
 * tarball capturing the repo's nervous-system snapshot, atrophy heatmap,
 * decisions, ghost clusters, top wisdom rules. New hires open the
 * tarball; their AI tool replays it chronologically; they go from
 * 0 → expert in 30 minutes instead of 6 months of interviews.
 *
 * Format: gzipped tar with a stable directory layout:
 *
 *   capsule/
 *   ├── manifest.json         — metadata + Mneme version + repo hash
 *   ├── nervous-system.json   — full team neuroanatomy snapshot
 *   ├── atrophy.json          — knowledge half-life heatmap
 *   ├── decisions.json        — auto-extracted ADRs
 *   ├── ghost-clusters.json   — half-finished features grouped by theme
 *   ├── promise-debt.json     — TODO/FIXME ledger
 *   ├── replay.md             — chronological narrative for AI consumption
 *   └── README.md             — what this capsule is + how to use it
 *
 * `--export` writes the tarball; `--import` unpacks it and stages a
 * replay.md the user can paste into their AI tool.
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync, rmSync, readdirSync, statSync } from "node:fs";
import { dirname, join, resolve, basename } from "node:path";
import { execSync, spawnSync } from "node:child_process";
import kleur from "kleur";
import { ui } from "../ui.js";
import { git, store, people, retrieve, util } from "@mneme-ai/core";
import { dbPath } from "../paths.js";
import { resolveEmbedder } from "@mneme-ai/embeddings";

export interface TimeCapsuleOptions {
  cwd: string;
  exportPath?: string;
  importPath?: string;
  quarter?: string;
  json?: boolean;
}

interface CapsuleManifest {
  capsuleVersion: 1;
  generatedAt: string;
  generatedByMneme: string;
  repoRoot: string;
  repoHash: string;
  quarter?: string;
  totalCommits: number;
  files: string[];
}

const CAPSULE_VERSION = 1;

function safeReadVersion(): string {
  try {
    const here = new URL(".", import.meta.url).pathname;
    // dist/commands/ → ../../package.json
    const pkgPath = resolve(here, "..", "..", "package.json");
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { version?: string };
    return pkg.version ?? "0.0.0";
  } catch {
    return "0.0.0";
  }
}

async function exportCapsule(opts: TimeCapsuleOptions): Promise<number> {
  const outPath = opts.exportPath!;
  if (!(await git.isGitRepo(opts.cwd))) {
    ui.error("Not in a git repo. Run `mneme init` first.");
    return 1;
  }
  const meta = await git.getRepoMeta(opts.cwd);
  const dbPathStr = dbPath(meta.rootPath);
  if (!existsSync(dbPathStr)) {
    ui.error("No Mneme index found. Run `mneme index` first.");
    return 1;
  }

  // Stage capsule contents in a temp directory
  const stageDir = join(meta.rootPath, ".mneme", "capsule-stage");
  if (existsSync(stageDir)) rmSync(stageDir, { recursive: true, force: true });
  mkdirSync(stageDir, { recursive: true });

  const s = new store.MnemeStore(dbPathStr);
  const totalCommits = s.countCommits();

  const filesGenerated: string[] = [];

  // 1 — nervous-system.json
  try {
    const ns = await people.buildNervousSystem(s, { topPeople: 10, cwd: meta.rootPath });
    if (ns) {
      const p = join(stageDir, "nervous-system.json");
      writeFileSync(p, JSON.stringify(ns, null, 2));
      filesGenerated.push("nervous-system.json");
    }
  } catch (err) {
    ui.warn(`nervous-system.json skipped: ${(err as Error).message}`);
  }

  // 2 — atrophy.json
  try {
    const a = people.atrophy(s, { topN: 30 });
    const p = join(stageDir, "atrophy.json");
    writeFileSync(p, JSON.stringify(a, null, 2));
    filesGenerated.push("atrophy.json");
  } catch (err) {
    ui.warn(`atrophy.json skipped: ${(err as Error).message}`);
  }

  // 3 — promise-debt.json (the TODO/FIXME ledger)
  try {
    const commits = util.loadAllCommits(s);
    const r = people.buildPromiseReport(commits);
    const p = join(stageDir, "promise-debt.json");
    writeFileSync(p, JSON.stringify(r, null, 2));
    filesGenerated.push("promise-debt.json");
  } catch (err) {
    ui.warn(`promise-debt.json skipped: ${(err as Error).message}`);
  }

  // 4 — replay.md (the chronological narrative the AI replays)
  const embedder = await resolveEmbedder({ provider: "auto" });
  let replay = `# ${meta.repo} — chronological replay\n\nGenerated by Mneme ${safeReadVersion()} · time-capsule v${CAPSULE_VERSION}\n\n`;
  replay += `> Open this file in your AI coding tool. Ask it to read top-to-bottom and summarise the key transitions.\n\n`;
  try {
    const decisionsResult = await retrieve.search("architectural decision OR migration OR refactor", {
      store: s,
      embedder,
      repo: meta,
      topK: 12,
    });
    replay += "## Top architectural moments\n\n";
    for (const r of decisionsResult) {
      const date = (r.commit.authorDate || "").slice(0, 10);
      replay += `- **${date} · ${r.commit.shortHash}** — ${r.commit.subject}\n`;
    }
    replay += "\n";
  } catch {}
  replay += "## How to use this capsule\n\n";
  replay += "1. Paste this `replay.md` into your AI tool (Claude Code / Cursor / Codex).\n";
  replay += "2. Ask: \"Summarise the major transitions in this repo over time. Which areas should a new engineer learn first?\"\n";
  replay += "3. Open `nervous-system.json` for the team-shape view.\n";
  replay += "4. Open `atrophy.json` to see knowledge half-life.\n";
  replay += "5. Open `promise-debt.json` for outstanding TODOs.\n";
  writeFileSync(join(stageDir, "replay.md"), replay);
  filesGenerated.push("replay.md");

  // 5 — README.md (capsule self-documentation)
  const cReadme = `# ${meta.repo} — Mneme Time Capsule\n\nA single-tarball snapshot of this repo's nervous system, atrophy state, decisions, and outstanding promise debt.\n\nGenerated: ${new Date().toISOString()}\n\nMneme version: ${safeReadVersion()}\n\n## What's inside\n\n- \`manifest.json\` — capsule metadata\n- \`replay.md\` — chronological narrative for AI replay\n- \`nervous-system.json\` — team neuroanatomy at the snapshot moment\n- \`atrophy.json\` — knowledge-decay heatmap\n- \`promise-debt.json\` — TODO/FIXME ledger\n\n## How to import\n\n\`\`\`bash\nmneme time-capsule --import path/to/this-capsule.tgz\n\`\`\`\n\nThen open \`replay.md\` in your AI tool.\n`;
  writeFileSync(join(stageDir, "README.md"), cReadme);
  filesGenerated.push("README.md");

  // 6 — manifest.json (last so we know the file list)
  const repoHash = (() => {
    try {
      return execSync("git rev-parse HEAD", { cwd: meta.rootPath }).toString().trim();
    } catch {
      return "unknown";
    }
  })();
  const manifest: CapsuleManifest = {
    capsuleVersion: CAPSULE_VERSION,
    generatedAt: new Date().toISOString(),
    generatedByMneme: safeReadVersion(),
    repoRoot: meta.rootPath,
    repoHash,
    quarter: opts.quarter,
    totalCommits,
    files: [...filesGenerated, "manifest.json"],
  };
  writeFileSync(join(stageDir, "manifest.json"), JSON.stringify(manifest, null, 2));

  // 7 — bundle as gzipped tar. Win10+ ships tar.exe; macOS/Linux always have it.
  // v1.9.0 adds an upfront probe + clear error if tar is missing.
  if (!existsSync(dirname(outPath))) mkdirSync(dirname(outPath), { recursive: true });
  const tarProbe = spawnSync("tar", ["--version"], { stdio: "pipe" });
  if (tarProbe.status !== 0) {
    ui.error(
      "Time capsule export requires `tar` on PATH. " +
        (process.platform === "win32"
          ? "Win10+ ships tar.exe; if you're on an older Windows, install Git for Windows or 7-Zip."
          : "Most macOS/Linux systems have tar pre-installed; install via your package manager."),
    );
    return 1;
  }
  // v1.82 Bug #2 fix: bsdtar (Windows 10+) parses `-f C:\path` as
  // `host:path` (treats C: as an SSH hostname). Fix by running tar in
  // dirname(outPath) with cwd, and passing only the basename to -f.
  // This sidesteps colon-host parsing entirely.
  const absOut = resolve(outPath);
  const outDirAbs = dirname(absOut);
  const outFile = basename(absOut);
  const tarRes = spawnSync("tar", ["-czf", outFile, "-C", stageDir, "."], {
    cwd: outDirAbs,
    stdio: "pipe",
  });
  if (tarRes.status !== 0) {
    ui.error(`tar failed: ${tarRes.stderr?.toString() ?? "unknown error"}`);
    return 1;
  }

  // Cleanup stage dir
  try {
    rmSync(stageDir, { recursive: true, force: true });
  } catch {}

  if (opts.json) {
    process.stdout.write(JSON.stringify({ exported: true, path: outPath, manifest }, null, 2) + "\n");
    return 0;
  }
  ui.banner();
  process.stdout.write(
    kleur.bold("\n  📦 Mneme — time capsule exported\n\n") +
      `  ${kleur.green("✓")} ${outPath}\n` +
      `      ${kleur.dim(`${manifest.totalCommits} commits · ${filesGenerated.length} artifacts · ${opts.quarter ?? "no quarter tag"}`)}\n\n` +
      kleur.bold("  Send to a new hire:\n") +
      `    1. Share the .tgz file (Slack, email, S3 — anywhere).\n` +
      `    2. They run: ${kleur.cyan("mneme time-capsule --import <file>")}\n` +
      `    3. They open ${kleur.cyan("replay.md")} in their AI tool.\n` +
      `    4. 30 minutes later → repo expert.\n\n`,
  );
  return 0;
}

async function importCapsule(opts: TimeCapsuleOptions): Promise<number> {
  const inPath = opts.importPath!;
  if (!existsSync(inPath)) {
    ui.error(`Capsule not found: ${inPath}`);
    return 1;
  }
  const outDir = join(opts.cwd, ".mneme", "capsule-imported");
  if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  // v1.82 Bug #2 fix (extract side): same colon-as-host issue.
  // cwd into dirname(inPath), pass basename(inPath) to -f.
  const absIn = resolve(inPath);
  const inDirAbs = dirname(absIn);
  const inFile = basename(absIn);
  const tarRes = spawnSync("tar", ["-xzf", inFile, "-C", resolve(outDir)], {
    cwd: inDirAbs,
    stdio: "pipe",
  });
  if (tarRes.status !== 0) {
    ui.error(`tar extract failed: ${tarRes.stderr?.toString() ?? "unknown"}`);
    return 1;
  }
  const manifestPath = join(outDir, "manifest.json");
  if (!existsSync(manifestPath)) {
    ui.error("Capsule has no manifest.json — invalid format");
    return 1;
  }
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as CapsuleManifest;
  if (manifest.capsuleVersion !== CAPSULE_VERSION) {
    ui.warn(`Capsule version ${manifest.capsuleVersion} ≠ tool version ${CAPSULE_VERSION} — proceeding but some artifacts may not parse.`);
  }

  if (opts.json) {
    process.stdout.write(JSON.stringify({ imported: true, into: outDir, manifest }, null, 2) + "\n");
    return 0;
  }
  ui.banner();
  process.stdout.write(
    kleur.bold("\n  📦 Mneme — time capsule imported\n\n") +
      `  ${kleur.green("✓")} unpacked into ${outDir}\n` +
      `      ${kleur.dim(`${manifest.totalCommits} commits · generated ${manifest.generatedAt} · Mneme ${manifest.generatedByMneme}`)}\n\n` +
      kleur.bold("  Open this in your AI tool:\n") +
      `    ${kleur.cyan(join(outDir, "replay.md"))}\n\n` +
      `  Ask your AI: "Summarise the major transitions in this repo. Which areas should I learn first?"\n\n`,
  );
  return 0;
}

export async function timeCapsuleCommand(opts: TimeCapsuleOptions): Promise<number> {
  if (opts.exportPath && opts.importPath) {
    ui.error("Pass --export OR --import, not both.");
    return 1;
  }
  if (!opts.exportPath && !opts.importPath) {
    // Default: export to a sensible path
    opts.exportPath = join(opts.cwd, `mneme-capsule-${new Date().toISOString().slice(0, 10)}.tgz`);
  }
  if (opts.exportPath) return exportCapsule(opts);
  return importCapsule(opts);
}
