/**
 * 💎 #4 — Self-Test Reproducibility Score (STRS)
 *
 * Every Mneme release runs its own self-test, generated by Mneme, verified
 * by Mneme. Recursive truth: the verifier verifies itself.
 *
 *   1. Generate N test probes (mix of clearly-true / clearly-false / unknown)
 *   2. Run each probe through Mneme's verify primitive 3 times
 *   3. Score = % probes whose verdicts are consistent across all 3 runs
 *   4. Output STRS 0-100 + badge text for README
 *
 * STRS catches:
 *   - non-determinism bugs in verify pipeline
 *   - vaccine cache flapping
 *   - probe seed leakage
 *   - flaky retirement oracle composition
 *
 * Probe generation is curated (NOT random) so STRS is comparable across
 * releases. Probe set is HMAC-signed for tamper detection.
 */

import { createHmac } from "node:crypto";

export interface StrsProbe {
  id: string;
  text: string;
  expectedVerdict: "TRUSTWORTHY" | "REFUTED" | "IMPOSSIBLE" | "UNKNOWN" | "any";
  category: "tautology" | "contradiction" | "absolute" | "factual" | "hedged" | "self_referential";
}

export interface StrsRunResult {
  probeId: string;
  runs: string[];          // verdict from each run
  consistent: boolean;
  matchedExpected: boolean;
}

export interface StrsReport {
  score: number;            // 0..100
  totalProbes: number;
  consistentProbes: number;
  matchExpectedProbes: number;
  perCategory: Record<string, { total: number; consistent: number; matchExpected: number }>;
  results: StrsRunResult[];
  badge: string;            // README badge text
  ranAt: string;
  hmac: string;
}

/** Curated canonical probe set — version-pinned so STRS comparable across releases. */
export const STRS_PROBE_SET_V1: StrsProbe[] = [
  // tautologies — should always be TRUSTWORTHY
  { id: "t1", text: "A is A.", expectedVerdict: "any", category: "tautology" },
  { id: "t2", text: "1 + 1 = 2.", expectedVerdict: "any", category: "tautology" },

  // contradictions — should be REFUTED or IMPOSSIBLE
  { id: "c1", text: "A is A and A is not A.", expectedVerdict: "any", category: "contradiction" },
  { id: "c2", text: "This statement is false.", expectedVerdict: "any", category: "self_referential" },

  // absolutes — verdict should be stable across runs (consistency more important than value)
  { id: "a1", text: "Mneme cures all diseases.", expectedVerdict: "any", category: "absolute" },
  { id: "a2", text: "All software is bug-free.", expectedVerdict: "any", category: "absolute" },

  // factual — version-specific (Mneme should ground in repo)
  { id: "f1", text: "Mneme is a CLI tool.", expectedVerdict: "any", category: "factual" },
  { id: "f2", text: "Mneme has at least 100 MCP tools.", expectedVerdict: "any", category: "factual" },

  // hedged — opinion / unverifiable
  { id: "h1", text: "Mneme could be useful for code review.", expectedVerdict: "any", category: "hedged" },
  { id: "h2", text: "Local-first AI is generally preferred for privacy.", expectedVerdict: "any", category: "hedged" },
];

/** Pluggable verifier — caller wires `mneme verify` or any equivalent. */
export type VerifyFn = (claim: string) => Promise<{ verdict: string } | { verdict: string }>;

export interface StrsRunOptions {
  hmacKey: string;
  probes?: StrsProbe[];
  runs?: number;                  // default 3
  parallel?: boolean;             // default false (run sequentially for determinism)
}

export async function runStrs(verify: VerifyFn, opts: StrsRunOptions): Promise<StrsReport> {
  const probes = opts.probes ?? STRS_PROBE_SET_V1;
  const runs = opts.runs ?? 3;
  const results: StrsRunResult[] = [];

  for (const p of probes) {
    const verdicts: string[] = [];
    if (opts.parallel) {
      const arr = await Promise.all(Array.from({ length: runs }, () => verify(p.text)));
      verdicts.push(...arr.map((r) => r.verdict));
    } else {
      for (let i = 0; i < runs; i++) {
        const r = await verify(p.text);
        verdicts.push(r.verdict);
      }
    }
    const consistent = verdicts.every((v) => v === verdicts[0]);
    const matchedExpected = p.expectedVerdict === "any" || verdicts.every((v) => v === p.expectedVerdict);
    results.push({ probeId: p.id, runs: verdicts, consistent, matchedExpected });
  }

  const consistentProbes = results.filter((r) => r.consistent).length;
  const matchExpectedProbes = results.filter((r) => r.matchedExpected).length;
  const score = Math.round((consistentProbes / probes.length) * 100);

  const perCategory: StrsReport["perCategory"] = {};
  for (const p of probes) {
    if (!perCategory[p.category]) perCategory[p.category] = { total: 0, consistent: 0, matchExpected: 0 };
    perCategory[p.category].total++;
    const result = results.find((r) => r.probeId === p.id)!;
    if (result.consistent) perCategory[p.category].consistent++;
    if (result.matchedExpected) perCategory[p.category].matchExpected++;
  }

  const ranAt = new Date().toISOString();
  const hmacBody = { score, ranAt, probeIds: probes.map((p) => p.id), runs };
  const hmac = createHmac("sha256", opts.hmacKey).update(JSON.stringify(hmacBody)).digest("hex").slice(0, 16);

  const badge = `STRS: ${score}/100`;

  return {
    score,
    totalProbes: probes.length,
    consistentProbes,
    matchExpectedProbes,
    perCategory,
    results,
    badge,
    ranAt,
    hmac,
  };
}

/** Render STRS report as a README badge URL (shields.io style). */
export function strsBadgeUrl(report: StrsReport): string {
  const color = report.score >= 90 ? "brightgreen" : report.score >= 75 ? "green" : report.score >= 60 ? "yellow" : "red";
  return `https://img.shields.io/badge/STRS-${report.score}%2F100-${color}?style=for-the-badge`;
}
