/**
 * v2.9.4 -- BEACON page template (extracted so the renderer file stays
 * readable). Bilingual TH/EN with toggle, centered layout, prominent
 * manual fallback, bilingual error messages on button failure.
 *
 * The HTML embeds a small i18n table so the JS toggle works WITHOUT any
 * network or framework — works on every browser including iOS Safari,
 * Android Chrome, Samsung Internet, Firefox, etc.
 */

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export interface PageVendor {
  name: string;
  url: string;
}

export function renderBeaconHtmlPage(payload: string, vendor: PageVendor, label: string): string {
  const safePayload = escapeHtml(payload);
  const vName = escapeHtml(vendor.name);
  const vUrl = escapeHtml(vendor.url);
  const vNameJs = vendor.name.replace(/[\\']/g, "\\$&");
  return [
    "<!doctype html>",
    "<html lang=\"th\"><head>",
    "<meta charset=\"utf-8\">",
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=5\">",
    `<title>${escapeHtml(label)}</title>`,
    "<style>",
    "*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}",
    "html,body{margin:0;padding:0;background:#f5f7fa}",
    "body{font-family:-apple-system,BlinkMacSystemFont,system-ui,\"Segoe UI\",Roboto,\"Sukhumvit Set\",\"Noto Sans Thai\",sans-serif;line-height:1.55;color:#1f2328}",
    ".wrap{max-width:560px;margin:0 auto;padding:18px 16px 36px;text-align:center}",
    ".topbar{display:flex;justify-content:flex-end;gap:6px;margin-bottom:8px}",
    ".lang-btn{font-size:.88em;padding:6px 12px;border:1px solid #d0d7de;background:#fff;border-radius:999px;cursor:pointer;color:#57606a;font-weight:600}",
    ".lang-btn.active{background:#1a73e8;color:#fff;border-color:#1a73e8}",
    "h1{font-size:1.35em;margin:.4em 0 .2em;color:#0d1117;font-weight:700}",
    ".lead{color:#57606a;margin:0 auto 18px;max-width:460px;font-size:.95em}",
    ".step{margin:22px 0 8px;font-size:1.02em;font-weight:700;color:#1f2328;text-align:left}",
    ".btn{display:block;width:100%;font-size:1.05em;padding:16px 18px;border:0;border-radius:12px;color:#fff;cursor:pointer;font-weight:700;text-align:center;text-decoration:none;margin:8px 0;box-shadow:0 1px 3px rgba(0,0,0,.08)}",
    ".btn-primary{background:#1a73e8}",
    ".btn-primary:active{background:#0d47a1;transform:translateY(1px)}",
    ".btn-vendor{background:#137333}",
    ".btn-vendor:active{background:#0b5a25;transform:translateY(1px)}",
    ".btn-secondary{background:#57606a;font-size:.95em;padding:12px 16px}",
    ".btn-secondary:active{background:#3d4148}",
    ".status{margin:10px auto;padding:10px 14px;border-radius:8px;font-weight:600;display:none;text-align:left}",
    ".status.show{display:block}",
    ".status.ok{background:#dafbe1;color:#116329;border:1px solid #2da44e}",
    ".status.err{background:#ffebe9;color:#82071e;border:1px solid #d1242f}",
    ".toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#24292f;color:#fff;padding:10px 18px;border-radius:999px;font-size:.95em;opacity:0;transition:opacity .25s;pointer-events:none;z-index:9}",
    ".toast.show{opacity:.95}",
    ".manual-box{background:#fff;border:1px solid #d0d7de;border-radius:10px;padding:14px;margin:14px 0;text-align:left}",
    ".manual-box h3{margin:0 0 8px;font-size:1em;color:#1f2328}",
    "pre{white-space:pre-wrap;word-break:break-word;background:#f6f8fa;border:1px solid #d0d7de;padding:10px;border-radius:6px;font-size:.78em;max-height:32vh;overflow:auto;text-align:left;-webkit-user-select:all;user-select:all}",
    ".footer{margin-top:30px;padding-top:14px;border-top:1px solid #e1e4e8;color:#8b949e;font-size:.82em}",
    ".hint{font-size:.88em;color:#57606a;margin:6px auto 0;text-align:left}",
    "[data-lang]{display:none}",
    ".block[data-lang]{display:none}",
    ".block[data-lang].on{display:block}",
    "span[data-lang].on{display:inline}",
    "</style></head><body>",
    "<div class=\"wrap\">",
    "  <div class=\"topbar\">",
    "    <button id=\"lang-th\" class=\"lang-btn active\" onclick=\"setLang('th')\">TH</button>",
    "    <button id=\"lang-en\" class=\"lang-btn\" onclick=\"setLang('en')\">EN</button>",
    "  </div>",
    `  <h1>${escapeHtml(label)}</h1>`,
    `  <p class="lead block on" data-lang="th">การส่งสมอง Mneme ข้ามอุปกรณ์ ไม่ต้องติดตั้งอะไรในเครื่องนี้ แค่กดปุ่มตามลำดับ → ส่งต่อให้ ${vName} ได้เลย</p>`,
    `  <p class="lead block" data-lang="en">Mneme cross-device brain transfer. No app install needed on this device. Tap the buttons below in order to hand off to ${vName}.</p>`,
    "  <div class=\"step\">",
    "    <span class=\"block on\" data-lang=\"th\">ขั้นที่ 1 — กดเพื่อคัดลอก</span>",
    "    <span class=\"block\" data-lang=\"en\">Step 1 — Copy the soul prompt</span>",
    "  </div>",
    "  <button id=\"cp\" class=\"btn btn-primary\" onclick=\"copyAndStatus()\">",
    "    <span data-lang=\"th\" class=\"on\">📋 คัดลอก Soul Prompt</span>",
    "    <span data-lang=\"en\">📋 Copy soul prompt</span>",
    "  </button>",
    "  <div class=\"status\" id=\"s\"></div>",
    "  <div class=\"step\">",
    `    <span class="block on" data-lang="th">ขั้นที่ 2 — เปิด ${vName} แล้ว paste</span>`,
    `    <span class="block" data-lang="en">Step 2 — Open ${vName} and paste</span>`,
    "  </div>",
    `  <a href="${vUrl}" target="_blank" rel="noopener" class="btn btn-vendor" id="open-vendor" onclick="markOpened()">`,
    `    <span data-lang="th" class="on">🚀 เปิด ${vName}</span>`,
    `    <span data-lang="en">🚀 Open ${vName}</span>`,
    "  </a>",
    `  <p class="hint block on" data-lang="th">เมื่อ ${vName} เปิดแล้ว → กดค้างที่ช่องพิมพ์ → Paste → ส่ง. AI จะอ่าน LIVE STATE block ที่ด้านบนของ prompt และคุยต่อจากที่ค้างไว้</p>`,
    `  <p class="hint block" data-lang="en">After ${vName} opens, long-press the chat box → Paste → Send. The receiving AI reads the LIVE STATE block at the top and continues your conversation.</p>`,
    "  <div class=\"manual-box\">",
    "    <h3>",
    "      <span class=\"block on\" data-lang=\"th\">📜 Soul Prompt (สำหรับคัดลอกแบบ manual)</span>",
    "      <span class=\"block\" data-lang=\"en\">📜 Soul prompt (manual copy fallback)</span>",
    "    </h3>",
    "    <p class=\"hint block on\" data-lang=\"th\">ถ้าปุ่มด้านบนใช้ไม่ได้ในเบราว์เซอร์ของคุณ — กดปุ่มสีเทาด้านล่าง หรือกดค้างที่ข้อความใน pre block → Copy</p>",
    "    <p class=\"hint block\" data-lang=\"en\">If the buttons above don't work in your browser, use the grey button below — or long-press the text in the pre block → Copy.</p>",
    "    <button class=\"btn btn-secondary\" onclick=\"copyManual()\">",
    "      <span data-lang=\"th\" class=\"on\">📋 คัดลอกจากกล่องนี้</span>",
    "      <span data-lang=\"en\">📋 Copy from this box</span>",
    "    </button>",
    `    <pre id="p">${safePayload}</pre>`,
    "  </div>",
    "  <div class=\"footer\">",
    "    <span class=\"block on\" data-lang=\"th\">เสิร์ฟโดย Mneme BEACON · เซิร์ฟเวอร์ชั่วคราว · ปิดอัตโนมัติหลังไม่มีคนเข้าใน 10 นาที · <span id=\"ts\"></span></span>",
    "    <span class=\"block\" data-lang=\"en\">Served by Mneme BEACON · ephemeral local server · auto-stops after 10 min idle · <span id=\"ts2\"></span></span>",
    "  </div>",
    "</div>",
    "<div class=\"toast\" id=\"toast\"></div>",
    "<script>",
    "var i18n = {",
    "  th: {",
    `    copied: '✓ คัดลอกแล้ว! แตะ \"เปิด ${vNameJs}\" ด้านบน แล้ว paste ในช่องแชท',`,
    "    copyFail: '⚠ คัดลอกอัตโนมัติไม่ได้ในเบราว์เซอร์นี้ — เลื่อนลงไปที่กล่อง \"Soul Prompt\" ด้านล่าง → กดปุ่มสีเทา หรือกดค้างที่ข้อความ → Copy',",
    "    noClipboard: '⚠ เบราว์เซอร์นี้ไม่รองรับ auto-copy — เลื่อนลงไปที่กล่อง \"Soul Prompt\" ด้านล่าง → กดปุ่มสีเทา หรือกดค้างที่ข้อความ → Copy',",
    `    manualOk: '✓ คัดลอกจากกล่อง manual แล้ว — เปิด ${vNameJs} แล้ว paste',`,
    "    manualFail: '⚠ คัดลอกไม่ได้ — เลือกข้อความใน pre block ด้านล่าง → กดค้าง → Copy ในเมนู',",
    "    toastCopied: 'คัดลอกแล้ว ✓'",
    "  },",
    "  en: {",
    `    copied: '✓ Copied! Tap \"Open ${vNameJs}\" above, then paste in the chat box.',`,
    "    copyFail: '⚠ Auto-copy not allowed in this browser — scroll down to the \"Soul Prompt\" box → tap the grey button, or long-press the text → Copy.',",
    "    noClipboard: '⚠ This browser does not support auto-copy — scroll down to the \"Soul Prompt\" box → tap the grey button, or long-press the text → Copy.',",
    `    manualOk: '✓ Copied from manual box — open ${vNameJs} and paste.',`,
    "    manualFail: '⚠ Copy failed — select the text in the pre block below → long-press → choose Copy from the menu.',",
    "    toastCopied: 'Copied ✓'",
    "  }",
    "};",
    "var curLang = 'th';",
    "function setLang(l){",
    "  curLang = l;",
    "  document.documentElement.lang = l;",
    "  var els = document.querySelectorAll('[data-lang]');",
    "  for (var i=0;i<els.length;i++){ if (els[i].dataset.lang === l) els[i].classList.add('on'); else els[i].classList.remove('on'); }",
    "  document.getElementById('lang-th').classList.toggle('active', l === 'th');",
    "  document.getElementById('lang-en').classList.toggle('active', l === 'en');",
    "  var sEl = document.getElementById('s');",
    "  var kind = sEl.dataset.kind;",
    "  if (kind && i18n[l][kind]) sEl.textContent = i18n[l][kind];",
    "}",
    "function setStatus(kind, klass){",
    "  var s = document.getElementById('s');",
    "  s.dataset.kind = kind;",
    "  s.textContent = i18n[curLang][kind];",
    "  s.className = 'status show ' + klass;",
    "}",
    "function showToast(text){",
    "  var t = document.getElementById('toast');",
    "  t.textContent = text;",
    "  t.classList.add('show');",
    "  setTimeout(function(){ t.classList.remove('show'); }, 2000);",
    "}",
    "function copyText(text){",
    "  if (navigator.clipboard && navigator.clipboard.writeText) {",
    "    return navigator.clipboard.writeText(text);",
    "  }",
    "  // Legacy fallback for browsers without async clipboard API",
    "  return new Promise(function(resolve, reject){",
    "    try {",
    "      var ta = document.createElement('textarea');",
    "      ta.value = text;",
    "      ta.style.position = 'fixed';",
    "      ta.style.opacity = '0';",
    "      document.body.appendChild(ta);",
    "      ta.select();",
    "      var ok = document.execCommand('copy');",
    "      document.body.removeChild(ta);",
    "      ok ? resolve() : reject(new Error('execCommand failed'));",
    "    } catch (e) { reject(e); }",
    "  });",
    "}",
    "function copyAndStatus(){",
    "  var el = document.getElementById('p');",
    "  copyText(el.textContent).then(function(){",
    "    setStatus('copied', 'ok');",
    "    showToast(i18n[curLang].toastCopied);",
    "  }).catch(function(){ setStatus('copyFail', 'err'); });",
    "}",
    "function copyManual(){",
    "  var el = document.getElementById('p');",
    "  copyText(el.textContent).then(function(){",
    "    setStatus('manualOk', 'ok');",
    "    showToast(i18n[curLang].toastCopied);",
    "  }).catch(function(){",
    "    var range = document.createRange();",
    "    range.selectNodeContents(el);",
    "    var sel = window.getSelection();",
    "    sel.removeAllRanges();",
    "    sel.addRange(range);",
    "    setStatus('manualFail', 'err');",
    "  });",
    "}",
    "function markOpened(){ /* hook for future telemetry */ }",
    "var ts = new Date().toLocaleString();",
    "document.getElementById('ts').textContent = ts;",
    "document.getElementById('ts2').textContent = ts;",
    "</script>",
    "</body></html>",
  ].join("\n");
}
