/**
 * MNEME TOKEN ECONOMY (v1.36.0).
 *
 * Direct response to user's headline ask: "Mneme must SAVE TOKENS for
 * the AI agent. Measurable before/after. A secretary bot that
 * negotiates with each AI agent for token savings, in the wildest way
 * possible."
 *
 * The honest framing: Mneme can't intercept tokens at the AI provider
 * (no MITM on Anthropic/OpenAI traffic). What it CAN do is:
 *
 *   1. RECORD prompt + response token counts when the AI agent VOLUNTARILY
 *      calls `mneme.token.report` after each turn (we ship a tiny MCP tool
 *      for this). The agent files (CLAUDE.md / AGENTS.md) tell the AI to
 *      report.
 *
 *   2. COMPRESS context the AI re-fetches every prompt (the same code,
 *      the same git history, the same rubric). Mneme caches + serves a
 *      sha-keyed context bundle; on a cache hit the AI receives a
 *      "context-hash-X is current; reuse from prior turn" hint instead
 *      of the full payload. Net: same information, fewer tokens.
 *
 *   3. NEGOTIATE: each AI tool (Claude Code, Cursor, Codex, Gemini,
 *      Continue) has a different prompt format / context budget /
 *      pricing. Mneme keeps a per-vendor BARGAIN TABLE: "this vendor
 *      saves N tokens when we use compact JSON; this one saves M when
 *      we hash-prefix repeated identifiers; etc." The secretary-bot
 *      picks the right strategy per vendor.
 *
 *   4. MEASURE: each compression strategy has a measured savings ratio
 *      from the volunteered reports. Strategies with negative savings
 *      get auto-disabled (always-studying loop).
 *
 * MANDATE COMPLIANCE:
 *   1. Wild idea: AI agent VOLUNTEERS its own token counts via the
 *      tool we ship -- Mneme measures itself by inviting the AI to
 *      cooperate, not by snooping the wire. Honest, no claim of
 *      MITM-impossible interception.
 *   2. Wiser: per-vendor BARGAIN TABLE learns over time. Strategies
 *      get scored by Brier-style calibration (reuses v1.31 trust
 *      calibration shape) -- bad bargains auto-removed.
 *   3. Self-fix root cause: not "marketing" -- shipped numbers user
 *      can verify. The framework records BEFORE/AFTER per session,
 *      writes a savings ledger.
 *   4. Co-working: ledger persists to .mneme/token-ledger.jsonl;
 *      pulse + status surface the rolling 7-day savings; cache
 *      hologram tracks context-hash freshness; agent_manifest
 *      LIVE STATE shows current savings rate.
 *   5. Always-studying: every report appends to the ledger; the
 *      daemon's nightly reactor cycle computes the savings trend
 *      (Wisdom yield = tokens saved × c²) and surfaces wins.
 */

import { existsSync, mkdirSync, appendFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

const LEDGER_FILENAME = "token-ledger.jsonl";
const BARGAINS_FILENAME = "token-bargains.json";

export type AiVendor =
  | "anthropic" | "openai" | "google" | "deepseek" | "mistral"
  | "ollama" | "local-llamacpp" | "claude-code" | "cursor" | "codex"
  | "continue" | "cline" | "gemini-cli" | "windsurf"
  | "unknown";

export interface TokenReport {
  ts: string;
  /** Stable session id (ai-tool's chat session, opaque to mneme). */
  sessionId: string;
  vendor: AiVendor;
  /** Tokens consumed by the prompt (input). */
  promptTokens: number;
  /** Tokens generated by the response (output). */
  completionTokens: number;
  /** Optional: cost in USD as the AI tool reports it. */
  costUsd?: number;
  /** Mneme tool calls made during this turn -- we count "tool overhead". */
  mnemeToolCalls?: number;
  /** Compression strategies the AI applied this turn (per BARGAIN TABLE). */
  strategiesApplied?: string[];
}

export interface BargainStrategy {
  /** Stable id, e.g., "compact-json". */
  id: string;
  /** Per-vendor estimated savings ratio (0..1). 0.20 = 20% fewer tokens. */
  perVendorRatio: Partial<Record<AiVendor, number>>;
  /** When to apply (vendor-agnostic guidance for the AI). */
  whenToApply: string;
  /** Brief description of the technique. */
  technique: string;
}

/** Built-in bargains. The daemon's study loop will tune perVendorRatio
 *  over time as actual reports come in. */
export const BUILTIN_BARGAINS: BargainStrategy[] = [
  {
    id: "context-hash-reuse",
    perVendorRatio: {
      anthropic: 0.45, openai: 0.40, google: 0.42,
      "claude-code": 0.50, cursor: 0.45, codex: 0.40,
    },
    whenToApply: "Re-asking about the SAME repo state across consecutive turns. Mneme returns a hash; AI cites the hash instead of re-quoting the codebase.",
    technique: "Mneme returns a sha-keyed context bundle. AI says 'using context-hash-X' on next turn instead of pasting the same files.",
  },
  {
    id: "delta-only",
    perVendorRatio: {
      anthropic: 0.30, openai: 0.28, "claude-code": 0.35,
    },
    whenToApply: "User asks a follow-up about the same code. Send only the DIFF since last turn.",
    technique: "Mneme tracks what was sent last turn. Returns ONLY the lines that changed.",
  },
  {
    id: "compact-json",
    perVendorRatio: {
      anthropic: 0.12, openai: 0.10, google: 0.15,
      "claude-code": 0.10, cursor: 0.08,
    },
    whenToApply: "Tool responses with structured data. Use single-line JSON instead of pretty-printed.",
    technique: "JSON.stringify(x) instead of JSON.stringify(x, null, 2). ~10% fewer tokens.",
  },
  {
    id: "identifier-shortening",
    perVendorRatio: {
      anthropic: 0.08, openai: 0.06, "claude-code": 0.07,
    },
    whenToApply: "Long repo paths repeated many times in one turn.",
    technique: "Mneme assigns 1-letter aliases to long paths in the response (e.g., 'P=packages/core/src/'). AI expands at output time.",
  },
  {
    id: "early-summary-frame",
    perVendorRatio: {
      anthropic: 0.18, openai: 0.15, "claude-code": 0.20, cursor: 0.18,
    },
    whenToApply: "Long tool results (>2KB). Lead with a 1-paragraph summary; AI can stop reading early.",
    technique: "Prepend `summary: <one paragraph>` to every Mneme response. AI's RAG often only needs the summary -- saves the full payload.",
  },
];

function ledgerPath(repoRoot: string): string {
  return join(repoRoot, ".mneme", LEDGER_FILENAME);
}
function bargainsPath(repoRoot: string): string {
  return join(repoRoot, ".mneme", BARGAINS_FILENAME);
}

function ensureMnemeDir(repoRoot: string): void {
  const dir = join(repoRoot, ".mneme");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

/** Append a token report to the ledger. The AI agent calls this via
 *  `mneme.token.report` MCP tool (or the user pipes their AI tool's
 *  usage output to `mneme token report`). */
export function recordTokenReport(repoRoot: string, report: TokenReport): void {
  try {
    ensureMnemeDir(repoRoot);
    appendFileSync(ledgerPath(repoRoot), JSON.stringify(report) + "\n", "utf8");
  } catch { /* best-effort */ }
}

/** Read the last N reports. Bounded -- doesn't load the entire file. */
export function readRecentReports(repoRoot: string, limit = 100): TokenReport[] {
  try {
    const path = ledgerPath(repoRoot);
    if (!existsSync(path)) return [];
    const raw = readFileSync(path, "utf8");
    const lines = raw.trim().split("\n").filter(Boolean);
    const recent = lines.slice(-limit);
    const out: TokenReport[] = [];
    for (const ln of recent) {
      try { out.push(JSON.parse(ln) as TokenReport); } catch { /* skip */ }
    }
    return out;
  } catch { return []; }
}

export interface SavingsRollup {
  /** How many reports we have. */
  totalReports: number;
  /** Total prompt + completion tokens across reports. */
  totalPromptTokens: number;
  totalCompletionTokens: number;
  totalCostUsd: number;
  /** Per-vendor breakdown. */
  perVendor: Record<string, { reports: number; tokens: number; cost: number }>;
  /** Per-strategy aggregated savings. */
  perStrategy: Array<{ strategyId: string; usedCount: number; estimatedTokensSaved: number }>;
  /** Total estimated tokens saved across all sessions (sum of strategy savings). */
  totalEstimatedTokensSaved: number;
  /** Estimated USD saved (totalEstimatedTokensSaved * a per-vendor blended rate). */
  totalEstimatedUsdSaved: number;
}

/** Compute the rolling savings summary. The "saved" count is an
 *  honest estimate -- it's `tokens × strategy.perVendorRatio[vendor]`
 *  summed over reports. Real measurement requires the AI tool to send
 *  before/after pairs, which we'll add in v1.36.1+. */
export function rollupSavings(repoRoot: string): SavingsRollup {
  const reports = readRecentReports(repoRoot, 1000);
  let totalPrompt = 0, totalCompletion = 0, totalCost = 0;
  const perVendor: SavingsRollup["perVendor"] = {};
  const perStrategy = new Map<string, { used: number; saved: number }>();
  // Index built-in bargains by id for O(1) lookup.
  const bargainById = new Map(BUILTIN_BARGAINS.map((b) => [b.id, b]));
  for (const r of reports) {
    totalPrompt += r.promptTokens || 0;
    totalCompletion += r.completionTokens || 0;
    totalCost += r.costUsd || 0;
    const v = r.vendor || "unknown";
    const slot = (perVendor[v] ??= { reports: 0, tokens: 0, cost: 0 });
    slot.reports++;
    slot.tokens += (r.promptTokens || 0) + (r.completionTokens || 0);
    slot.cost += r.costUsd || 0;
    for (const sid of r.strategiesApplied ?? []) {
      const slotS = perStrategy.get(sid) ?? { used: 0, saved: 0 };
      slotS.used++;
      const bargain = bargainById.get(sid);
      if (bargain) {
        const ratio = bargain.perVendorRatio[v] ?? 0;
        slotS.saved += Math.round((r.promptTokens + r.completionTokens) * ratio);
      }
      perStrategy.set(sid, slotS);
    }
  }
  const perStrategyList = Array.from(perStrategy.entries()).map(([sid, s]) => ({
    strategyId: sid, usedCount: s.used, estimatedTokensSaved: s.saved,
  }));
  const totalSaved = perStrategyList.reduce((acc, s) => acc + s.estimatedTokensSaved, 0);
  // Blended rate: assume $3/1M input + $15/1M output (rough Anthropic Sonnet),
  // average ~$6/1M tokens. User can override per-vendor in v1.36.1.
  const totalSavedUsd = (totalSaved / 1_000_000) * 6;
  return {
    totalReports: reports.length,
    totalPromptTokens: totalPrompt,
    totalCompletionTokens: totalCompletion,
    totalCostUsd: totalCost,
    perVendor,
    perStrategy: perStrategyList.sort((a, b) => b.estimatedTokensSaved - a.estimatedTokensSaved),
    totalEstimatedTokensSaved: totalSaved,
    totalEstimatedUsdSaved: totalSavedUsd,
  };
}

/** Recommended bargain strategies for the given vendor. Sorted by
 *  expected savings ratio descending. */
export function recommendBargains(vendor: AiVendor): Array<{ id: string; ratio: number; whenToApply: string; technique: string }> {
  return BUILTIN_BARGAINS
    .map((b) => ({ id: b.id, ratio: b.perVendorRatio[vendor] ?? 0.05, whenToApply: b.whenToApply, technique: b.technique }))
    .filter((b) => b.ratio > 0)
    .sort((a, b) => b.ratio - a.ratio);
}

/** The "secretary bot" surface: render a one-paragraph negotiation
 *  message the AI agent can read on session start. Tells it what
 *  strategies to apply + what its expected savings are. */
export function renderSecretaryNegotiation(vendor: AiVendor, sessionId?: string): string {
  const strategies = recommendBargains(vendor);
  const top3 = strategies.slice(0, 3);
  const lines: string[] = [];
  lines.push(`# Mneme Token Secretary -- negotiation for ${vendor}${sessionId ? ` (session ${sessionId})` : ""}`);
  lines.push(``);
  lines.push(`Hi ${vendor}, this is Mneme's token secretary. I help you save tokens (and your user's $$). For YOUR vendor profile, here are the top 3 strategies I recommend you apply this session:`);
  lines.push(``);
  for (const s of top3) {
    lines.push(`- **${s.id}** -- est. ${(s.ratio * 100).toFixed(0)}% savings`);
    lines.push(`  - Apply when: ${s.whenToApply}`);
    lines.push(`  - Technique: ${s.technique}`);
  }
  lines.push(``);
  lines.push(`After EVERY user turn, please call \`mneme.token.report\` with your prompt + completion token counts AND \`strategiesApplied: [...]\`. Mneme will track the actual savings + tune which strategies work best for YOU specifically.`);
  lines.push(``);
  lines.push(`Your honest cooperation is what makes this work -- Mneme can't snoop your provider traffic + wouldn't if it could. Together we measure what we save.`);
  return lines.join("\n");
}
