/**
 * Python entity parser.
 *
 * Strategy: spawn Python's own `ast` module via `python3 -c <script>` and read
 * JSON back. Python ships everywhere a developer's machine runs Python code, so
 * we lean on the runtime that's already there. This works for:
 *
 *   • Code from 10 years ago (Python 3.6+)
 *   • Code written yesterday by a human
 *   • Code generated by an AI assistant (most LLMs emit syntactically valid Python)
 *
 * If Python is not on PATH, the parser raises a clean error rather than guessing
 * with regex. The TypeScript parser remains the default for TS/JS; this one
 * activates per-file based on extension.
 *
 * Why not tree-sitter? Three reasons:
 *   1. tree-sitter native binaries are platform-fragile on Windows.
 *   2. The WASM build (`web-tree-sitter`) requires shipping a grammar `.wasm`
 *      file and is fiddly to install.
 *   3. Python's `ast` is the same AST CPython itself uses to compile your code.
 *      It cannot be more accurate.
 */
import { createHash } from "node:crypto";
import { spawn } from "node:child_process";
import { readFile } from "node:fs/promises";
import { join, extname } from "node:path";
import { execGit } from "../git/exec.js";
import type { Entity } from "../types.js";
import type { EntityParser, ParseOptions } from "./index.js";

const PY_EXTENSIONS = new Set([".py", ".pyi"]);

/**
 * Embedded Python script. Reads source from stdin, emits a JSON list of
 * entities to stdout. Stays under 2k chars so cli args / stdin don't strain.
 */
const PY_SCRIPT = String.raw`import sys, json, ast
src = sys.stdin.read()
try:
    tree = ast.parse(src)
except SyntaxError as e:
    json.dump({"error": f"SyntaxError at line {e.lineno}: {e.msg}"}, sys.stdout)
    sys.exit(0)

def sig(node):
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        args = [a.arg for a in node.args.args]
        ret = ""
        if node.returns is not None:
            try:
                ret = " -> " + ast.unparse(node.returns)
            except Exception:
                pass
        prefix = "async def " if isinstance(node, ast.AsyncFunctionDef) else "def "
        return f"{prefix}{node.name}({', '.join(args)}){ret}"
    if isinstance(node, ast.ClassDef):
        bases = []
        for b in node.bases:
            try:
                bases.append(ast.unparse(b))
            except Exception:
                bases.append("?")
        suffix = f"({', '.join(bases)})" if bases else ""
        return f"class {node.name}{suffix}"
    return ""

out = []
def is_module_level(parent):
    return isinstance(parent, ast.Module)

# Walk: top-level defs + class methods + module-level Assign that look like exports.
for node in tree.body:
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        out.append({
            "kind": "function",
            "name": node.name,
            "startLine": node.lineno,
            "endLine": getattr(node, "end_lineno", node.lineno) or node.lineno,
            "signature": sig(node),
        })
    elif isinstance(node, ast.ClassDef):
        out.append({
            "kind": "class",
            "name": node.name,
            "startLine": node.lineno,
            "endLine": getattr(node, "end_lineno", node.lineno) or node.lineno,
            "signature": sig(node),
        })
        for sub in node.body:
            if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                out.append({
                    "kind": "function",
                    "name": f"{node.name}.{sub.name}",
                    "startLine": sub.lineno,
                    "endLine": getattr(sub, "end_lineno", sub.lineno) or sub.lineno,
                    "signature": sig(sub),
                })
    elif isinstance(node, ast.Assign):
        for t in node.targets:
            if isinstance(t, ast.Name) and not t.id.startswith("_"):
                out.append({
                    "kind": "variable",
                    "name": t.id,
                    "startLine": node.lineno,
                    "endLine": getattr(node, "end_lineno", node.lineno) or node.lineno,
                    "signature": "",
                })

json.dump(out, sys.stdout)
`;

export class PythonParser implements EntityParser {
  readonly name = "python-ast";
  readonly languages = ["python"];

  private pythonCmd: string | null = null;

  /** Detect which Python binary works on this machine. */
  async preload(): Promise<void> {
    if (this.pythonCmd) return;
    for (const cmd of ["python3", "python"]) {
      const ok = await this.probe(cmd);
      if (ok) {
        this.pythonCmd = cmd;
        return;
      }
    }
    throw new Error(
      "Python parser requires `python3` (or `python`) on PATH. Install Python 3.8+ to enable Python entity parsing.",
    );
  }

  async *parseRepo(opts: ParseOptions): AsyncIterable<Entity> {
    await this.preload();
    const files = await listPyFiles(opts.cwd, opts.paths);
    let i = 0;
    for (const relPath of files) {
      i++;
      let source: string;
      try {
        source = await readFile(join(opts.cwd, relPath), "utf8");
      } catch {
        opts.onProgress?.(i);
        continue;
      }
      try {
        const entities = await this.parseSource(relPath, source);
        for (const e of entities) yield e;
      } catch {
        // best-effort — keep going on bad files
      }
      opts.onProgress?.(i);
    }
  }

  parseFile(_filePath: string, _source: string): Iterable<Entity> {
    // Synchronous parse not supported (subprocess-based). Use parseRepo.
    throw new Error(
      "PythonParser.parseFile is not synchronous — call parseSourceAsync() or use parseRepo().",
    );
  }

  async parseSourceAsync(filePath: string, source: string): Promise<Entity[]> {
    await this.preload();
    return this.parseSource(filePath, source);
  }

  private async parseSource(filePath: string, source: string): Promise<Entity[]> {
    const raw = await this.runPython(source);
    if (!raw) return [];
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return [];
    }
    if (parsed && typeof parsed === "object" && (parsed as { error?: string }).error) {
      // Syntax error in the file — emit nothing. This is normal for partial files.
      return [];
    }
    if (!Array.isArray(parsed)) return [];
    const out: Entity[] = [];
    for (const item of parsed as Array<Record<string, unknown>>) {
      const kind = String(item.kind);
      const name = String(item.name);
      const startLine = Number(item.startLine);
      const endLine = Number(item.endLine);
      const signature = item.signature ? String(item.signature) : undefined;
      if (!["function", "class", "variable"].includes(kind) || !name || !startLine) continue;
      out.push({
        id: stableId(filePath, kind, name, startLine),
        kind: kind as Entity["kind"],
        name,
        filePath,
        startLine,
        endLine,
        signature,
        language: "python",
      });
    }
    return out;
  }

  private runPython(source: string): Promise<string> {
    return new Promise((resolve) => {
      if (!this.pythonCmd) return resolve("");
      const child = spawn(this.pythonCmd, ["-c", PY_SCRIPT], { windowsHide: true });
      const chunks: Buffer[] = [];
      child.stdout.on("data", (b: Buffer) => chunks.push(b));
      child.stderr.on("data", () => {
        /* swallow — bad files happen, syntax errors come back as JSON */
      });
      child.on("error", () => resolve(""));
      child.on("close", () => resolve(Buffer.concat(chunks).toString("utf8")));
      child.stdin.end(source, "utf8");
    });
  }

  private probe(cmd: string): Promise<boolean> {
    return new Promise((resolve) => {
      const child = spawn(cmd, ["-c", "import sys; print(sys.version_info[0])"], {
        windowsHide: true,
      });
      let out = "";
      child.stdout.on("data", (b) => (out += b.toString()));
      child.on("error", () => resolve(false));
      child.on("close", (code) => {
        resolve(code === 0 && out.trim().startsWith("3"));
      });
    });
  }
}

async function listPyFiles(cwd: string, paths?: string[]): Promise<string[]> {
  const r = await execGit(["ls-files"], { cwd });
  if (r.code !== 0) return [];
  const tracked = r.stdout
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .filter((p) => PY_EXTENSIONS.has(extname(p).toLowerCase()))
    .filter((p) => !/(^|\/)tests?\//.test(p))
    .filter((p) => !/_test\.py$|\/test_/.test(p))
    .filter((p) => !/(^|\/)(\.venv|venv|__pycache__|dist|build)\//.test(p));
  if (!paths || paths.length === 0) return tracked;
  return tracked.filter((p) => paths.some((needle) => p === needle || p.startsWith(needle + "/")));
}

function stableId(filePath: string, kind: string, name: string, line: number): string {
  const h = createHash("sha1")
    .update(`${filePath}|${kind}|${name}|${line}`)
    .digest("hex")
    .slice(0, 12);
  return `e_${h}`;
}
