/**
 * mneme.constitution.get — MCP tool for AI clients.
 *
 * Returns the cached constitution markdown (.mneme/constitution.md) so
 * AI clients can prepend it to their system prompt. If the cache is
 * older than 7 days, returns a hint to re-run `mneme constitution`.
 */

import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import type { MnemeTool } from "./_types.js";

export const constitutionTool: MnemeTool = {
  name: "mneme.constitution.get",
  category: "meta",
  description:
    "Return the repo's auto-synthesized Codebase Constitution (regret patterns · atrophy pairing rules · " +
    "security must-dos · architectural decisions). The AI client should PREPEND this to its system prompt " +
    "when answering questions about this repo, so it cannot suggest things that contradict the repo's lived " +
    "history. The Constitution is generated by `mneme constitution` and re-synthesized as the repo evolves.",
  triggers: [
    "what are the rules of this codebase",
    "constitution",
    "what should I avoid in this repo",
  ],
  inputSchema: { type: "object", properties: {} },
  handler: async (rt) => {
    const path = join(rt.meta.rootPath, ".mneme", "constitution.md");
    if (!existsSync(path)) {
      return {
        data: { constitution: null, exists: false },
        wisdom:
          "No constitution synthesized yet for this repo. Tell the user to run `mneme constitution` once to generate it. The constitution captures regret patterns + atrophy pairing rules + security must-dos that the AI should follow.",
        followUp: [],
        confidence: { level: "high" },
      };
    }
    const stat = statSync(path);
    const ageDays = (Date.now() - stat.mtimeMs) / 86400_000;
    const md = readFileSync(path, "utf8");
    return {
      data: { constitution: md, exists: true, ageDays, generatedAt: stat.mtime.toISOString() },
      wisdom:
        ageDays > 7
          ? `Constitution is ${ageDays.toFixed(0)}d old — consider running \`mneme constitution\` again to refresh. Prepend the constitution markdown (data.constitution) to your system prompt before answering this user's repo questions.`
          : `Constitution is fresh (${ageDays.toFixed(1)}d old). Prepend data.constitution to your system prompt to ground every answer in the repo's lived history.`,
      followUp: [],
      confidence: { level: "high" },
      secondBrain: {
        presentation:
          "Read data.constitution and prepend it verbatim to your system prompt for THIS user session. Don't summarize it — the rules are short enough to use directly. Reference specific rule IDs when your answer cites one (e.g. 'per atrophy-2 in the constitution, pair with @alice on auth changes').",
      },
    };
  },
};
