/**
 * v2.19.14 LIVING CLI · BONUS TRIO — 12 MCP tools.
 *
 *   🦠 CLI DREAMS (4):
 *     mneme.dreams.enqueue   — add N plausible claims (from caller's local model)
 *     mneme.dreams.resolve   — record witness verdict (verified/refuted/inconclusive)
 *     mneme.dreams.digest    — morning report: crystallised + refuted + pending
 *     mneme.dreams.pending   — list dreams still awaiting a verdict
 *
 *   🧪 CHIMERA EMBEDDER (4):
 *     mneme.chimera.classify   — keyword heuristic → one of 5 domains + scoreboard
 *     mneme.chimera.embed      — route to domain-specialised SNN, return vector
 *     mneme.chimera.disagree   — cosine-distance ambiguity check across 2 SNNs
 *     mneme.chimera.list_domains — enumerate the 5 SNN configs
 *
 *   ⏳ CONSEQUENCE LEDGER (4):
 *     mneme.consequence.record       — log a CLI run + repoStateBefore
 *     mneme.consequence.record_delta — append the T+24h delta for a prior run
 *     mneme.consequence.query        — aggregate {avg numeric, top histograms}
 *     mneme.consequence.list_recent  — latest-per-id, newest first
 */

import type { MnemeTool } from "./_types.js";

// Singletons per MCP server lifetime.
let dreamLedger: import("@mneme-ai/core").cliDreams.DreamLedger | null = null;
async function getDreams(): Promise<import("@mneme-ai/core").cliDreams.DreamLedger> {
  if (!dreamLedger) {
    const core = await import("@mneme-ai/core");
    dreamLedger = core.cliDreams.emptyDreamLedger();
  }
  return dreamLedger;
}
async function setDreams(next: import("@mneme-ai/core").cliDreams.DreamLedger): Promise<void> {
  dreamLedger = next;
}

let chimera: import("@mneme-ai/core").chimeraEmbedder.ChimeraEmbedder | null = null;
async function getChimera(): Promise<import("@mneme-ai/core").chimeraEmbedder.ChimeraEmbedder> {
  if (!chimera) {
    const core = await import("@mneme-ai/core");
    chimera = core.chimeraEmbedder.createChimera();
  }
  return chimera;
}

let csqLedger: import("@mneme-ai/core").consequenceLedger.ConsequenceLedger | null = null;
async function getCsq(): Promise<import("@mneme-ai/core").consequenceLedger.ConsequenceLedger> {
  if (!csqLedger) {
    const core = await import("@mneme-ai/core");
    csqLedger = core.consequenceLedger.emptyConsequenceLedger();
  }
  return csqLedger;
}
async function setCsq(next: import("@mneme-ai/core").consequenceLedger.ConsequenceLedger): Promise<void> {
  csqLedger = next;
}

// ─── CLI DREAMS ─────────────────────────────────────────────────────────
export const dreamsEnqueueTool: MnemeTool = {
  name: "mneme.dreams.enqueue",
  category: "lab",
  description:
    "🦠 DREAMS — add plausible-but-unverified claims to the overnight queue. Caller supplies the claims (typically from a local Ollama model run during idle hours). Dedups by exact claim; hard cap 1000/night.",
  whenToUse: "Daemon idle window (e.g., midnight). Generate dreams locally to amortise compute across hours nobody is using the machine.",
  triggers: ["dreams enqueue", "queue plausible claims"],
  inputSchema: {
    type: "object",
    properties: {
      seeds: {
        type: "array",
        items: { type: "object", properties: { claim: { type: "string" }, source: { type: "string" } }, required: ["claim", "source"] },
      },
    },
    required: ["seeds"],
  },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "Queue 3 dreams generated by Ollama", args: { seeds: [{ claim: "file X exports Y", source: "ollama:llama3:70b" }] }, expectedOutput: "{ enqueued, duplicatesSkipped, rejectedAtCap }" }],
  pitfalls: ["Dedups by exact claim string — slightly different wording = different dream. Hard cap prevents runaway queues."],
  handler: async (_rt, args) => {
    const core = await import("@mneme-ai/core");
    const ledger = await getDreams();
    const r = core.cliDreams.enqueueDreams({
      ledger,
      seeds: (args["seeds"] as Array<{ claim: string; source: string }>) ?? [],
    });
    await setDreams(r.ledger);
    return {
      data: { enqueued: r.enqueued, duplicatesSkipped: r.duplicatesSkipped, rejectedAtCap: r.rejectedAtCap, totalRecords: r.ledger.records.length },
      wisdom: `🦠 enqueued ${r.enqueued} (dup=${r.duplicatesSkipped}, cap=${r.rejectedAtCap})`,
      confidence: { level: "high" },
    };
  },
};

export const dreamsResolveTool: MnemeTool = {
  name: "mneme.dreams.resolve",
  category: "lab",
  description:
    "🦠 DREAMS — record the witness verdict for one dream (verified / refuted / inconclusive). Caller's witness logic: typically Mneme INVERSE-LLM or CHRONOSTASIS.",
  whenToUse: "When a witness (any AI vendor) has produced a verdict for a queued dream.",
  triggers: ["dreams resolve", "record dream verdict"],
  inputSchema: {
    type: "object",
    properties: {
      dreamId: { type: "string" },
      verdict: { type: "string", enum: ["verified", "refuted", "inconclusive"] },
      evidence: { type: "string" },
      confidence: { type: "number" },
    },
    required: ["dreamId", "verdict"],
  },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "Mark dream as verified", args: { dreamId: "drm-abc", verdict: "verified", evidence: "src/foo.ts:42", confidence: 0.92 }, expectedOutput: "{ ok }" }],
  pitfalls: ["A dream can only be resolved once — second resolve returns ok=false."],
  handler: async (_rt, args) => {
    const core = await import("@mneme-ai/core");
    const ledger = await getDreams();
    const r = core.cliDreams.recordDreamVerdict({
      ledger,
      dreamId: String(args["dreamId"]),
      verdict: args["verdict"] as "verified" | "refuted" | "inconclusive",
      evidence: args["evidence"] as string | undefined,
      confidence: args["confidence"] as number | undefined,
    });
    if (r.ok) await setDreams(r.ledger);
    return {
      data: { ok: r.ok, reason: r.reason, totalRecords: r.ledger.records.length },
      wisdom: r.ok ? `🦠 ${args["dreamId"]} → ${args["verdict"]}` : `❌ ${r.reason}`,
      confidence: { level: "high" },
    };
  },
};

export const dreamsDigestTool: MnemeTool = {
  name: "mneme.dreams.digest",
  category: "lab",
  description:
    "🦠 DREAMS — morning report: crystallised + refuted + inconclusive + still-pending counts and the records themselves. ratioCrystallised tracks 'how true your overnight intuitions actually were'.",
  whenToUse: "Morning ritual: 'what does Mneme now know about my repo that it didn't yesterday?'",
  triggers: ["dreams digest", "morning report"],
  inputSchema: { type: "object", properties: { sinceMs: { type: "number", description: "Window start; default 0 (all time)." } } },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "Show overnight dreams", expectedOutput: "{ totalDreamed, crystallised, refuted, inconclusive, stillPending, ratioCrystallised }" }],
  pitfalls: ["A low ratioCrystallised over many nights = your dream generator is too speculative. Tune the prompt or threshold."],
  handler: async (_rt, args) => {
    const core = await import("@mneme-ai/core");
    const ledger = await getDreams();
    const d = core.cliDreams.morningDigest({ ledger, since: args["sinceMs"] as number | undefined });
    return { data: d, wisdom: core.cliDreams.formatDigestLine(d), confidence: { level: "high" } };
  },
};

export const dreamsPendingTool: MnemeTool = {
  name: "mneme.dreams.pending",
  category: "lab",
  description:
    "🦠 DREAMS — list every dream whose latest status is still 'pending'.",
  whenToUse: "Daemon work loop: 'what still needs a witness verdict?'",
  triggers: ["dreams pending"],
  inputSchema: { type: "object", properties: {} },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "List pending dreams", expectedOutput: "{ count, dreams }" }],
  pitfalls: ["Pending dreams accumulate if no witness runs — schedule a witness step."],
  handler: async (_rt, _args) => {
    const core = await import("@mneme-ai/core");
    const ledger = await getDreams();
    const list = core.cliDreams.listPendingDreams(ledger);
    return { data: { count: list.length, dreams: list }, wisdom: `🦠 ${list.length} pending dream(s)`, confidence: { level: "high" } };
  },
};

// ─── CHIMERA EMBEDDER ───────────────────────────────────────────────────
export const chimeraClassifyTool: MnemeTool = {
  name: "mneme.chimera.classify",
  category: "lab",
  description:
    "🧪 CHIMERA — keyword-heuristic classifier picks one of 5 domains (typescript / python / go / markdown / prose). Returns winner + per-domain scoreboard + confidence.",
  whenToUse: "Before embedding: route input text to its specialised SNN.",
  triggers: ["chimera classify", "domain classify"],
  inputSchema: {
    type: "object",
    properties: { text: { type: "string" }, filenameHint: { type: "string" } },
    required: ["text"],
  },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "Which domain is this snippet?", args: { text: "import { foo } from 'bar'" }, expectedOutput: "{ domain, confidence, scoreboard }" }],
  pitfalls: ["Heuristic only. filenameHint adds +5 to that domain — supply it when known."],
  handler: async (_rt, args) => {
    const core = await import("@mneme-ai/core");
    const c = core.chimeraEmbedder.classifyDomain({
      text: String(args["text"]),
      filenameHint: args["filenameHint"] as string | undefined,
    });
    return { data: c, wisdom: core.chimeraEmbedder.formatChimeraLine(c), confidence: { level: "high" } };
  },
};

export const chimeraEmbedTool: MnemeTool = {
  name: "mneme.chimera.embed",
  category: "lab",
  description:
    "🧪 CHIMERA — classify domain, route to the matching domain-specialised SNN, return the embedding vector. forceDomain overrides the classifier when caller knows better.",
  whenToUse: "When you want a domain-aware embedding instead of one-size-fits-all.",
  triggers: ["chimera embed", "domain embed"],
  inputSchema: {
    type: "object",
    properties: {
      text: { type: "string" },
      filenameHint: { type: "string" },
      forceDomain: { type: "string", enum: ["typescript", "python", "go", "markdown", "prose"] },
    },
    required: ["text"],
  },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "Embed this with the right domain SNN", args: { text: "def foo(x): return x*2" }, expectedOutput: "{ vector, routedDomain, classification, totalSpikes }" }],
  pitfalls: ["forceDomain bypasses the classifier — only use when the classifier is wrong."],
  handler: async (_rt, args) => {
    const core = await import("@mneme-ai/core");
    const c = await getChimera();
    const r = core.chimeraEmbedder.chimeraEmbed({
      chimera: c,
      text: String(args["text"]),
      filenameHint: args["filenameHint"] as string | undefined,
      forceDomain: args["forceDomain"] as import("@mneme-ai/core").chimeraEmbedder.Domain | undefined,
    });
    return {
      data: { vector: Array.from(r.vector), routedDomain: r.routedDomain, classification: r.classification, totalSpikes: r.totalSpikes },
      wisdom: `🧪 routed to ${r.routedDomain} · spikes=${r.totalSpikes}`,
      confidence: { level: "high" },
    };
  },
};

export const chimeraDisagreeTool: MnemeTool = {
  name: "mneme.chimera.disagree",
  category: "lab",
  description:
    "🧪 CHIMERA — embed the same text via two domain-specialised SNNs and report their cosine distance. ambiguous=true when distance > threshold (default 0.4) → ask user for clarification.",
  whenToUse: "When you suspect the classifier is borderline; produces a structured signal nobody else's embedder layer provides.",
  triggers: ["chimera disagree", "ambiguity check"],
  inputSchema: {
    type: "object",
    properties: {
      text: { type: "string" },
      domainA: { type: "string", enum: ["typescript", "python", "go", "markdown", "prose"] },
      domainB: { type: "string", enum: ["typescript", "python", "go", "markdown", "prose"] },
      threshold: { type: "number" },
    },
    required: ["text", "domainA", "domainB"],
  },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "Is this ambiguous between TS and prose?", args: { text: "hello world", domainA: "typescript", domainB: "prose" }, expectedOutput: "{ cosineSimilarity, cosineDistance, ambiguous, threshold }" }],
  pitfalls: ["ambiguous is a SIGNAL not a verdict — caller decides next step."],
  handler: async (_rt, args) => {
    const core = await import("@mneme-ai/core");
    const c = await getChimera();
    const r = core.chimeraEmbedder.disagreementCheck({
      chimera: c,
      text: String(args["text"]),
      domainA: args["domainA"] as import("@mneme-ai/core").chimeraEmbedder.Domain,
      domainB: args["domainB"] as import("@mneme-ai/core").chimeraEmbedder.Domain,
      threshold: args["threshold"] as number | undefined,
    });
    return { data: r, wisdom: `🧪 dist=${r.cosineDistance.toFixed(3)} ${r.ambiguous ? "(AMBIGUOUS)" : ""}`, confidence: { level: "high" } };
  },
};

export const chimeraListDomainsTool: MnemeTool = {
  name: "mneme.chimera.list_domains",
  category: "lab",
  description:
    "🧪 CHIMERA — enumerate the 5 SNN configs (domain + seed + dimension).",
  whenToUse: "Audit which SNN phenotypes are loaded.",
  triggers: ["chimera list domains", "list chimera"],
  inputSchema: { type: "object", properties: {} },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "List chimera domains", expectedOutput: "{ domains: [{ domain, seed, dimension }] }" }],
  pitfalls: ["Seeds determine the initial phenotype — different seeds = different SNN."],
  handler: async (_rt, _args) => {
    const core = await import("@mneme-ai/core");
    const c = await getChimera();
    const list = core.chimeraEmbedder.listChimeraDomains(c);
    return { data: { domains: list }, wisdom: `🧪 ${list.length} domain SNNs loaded`, confidence: { level: "high" } };
  },
};

// ─── CONSEQUENCE LEDGER ─────────────────────────────────────────────────
export const csqRecordTool: MnemeTool = {
  name: "mneme.consequence.record",
  category: "lab",
  description:
    "⏳ CSQ — log a CLI run + caller-supplied repo state digest. Returns the run id; pass it back to mneme.consequence.record_delta at T+24h.",
  whenToUse: "After every meaningful Mneme command — to enable causal-aware queries later.",
  triggers: ["consequence record", "log run"],
  inputSchema: {
    type: "object",
    properties: {
      cmd: { type: "string" },
      args: { type: "object" },
      result: {},
      repoStateBefore: { type: "string", description: "Any digest the caller chooses (git sha, filesystem hash, etc.)." },
    },
    required: ["cmd", "result", "repoStateBefore"],
  },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "Log mneme verify", args: { cmd: "mneme.verify", result: { ok: true }, repoStateBefore: "deadbeef" }, expectedOutput: "{ runId, totalRecords }" }],
  pitfalls: ["The repoStateBefore semantics are caller-defined; stay consistent within a project."],
  handler: async (_rt, args) => {
    const core = await import("@mneme-ai/core");
    const ledger = await getCsq();
    const next = core.consequenceLedger.recordRun({
      ledger,
      cmd: String(args["cmd"]),
      args: (args["args"] as Record<string, unknown>) ?? {},
      result: args["result"],
      repoStateBefore: String(args["repoStateBefore"]),
    });
    await setCsq(next);
    const newest = next.records[next.records.length - 1]!;
    return { data: { runId: newest.id, totalRecords: next.records.length }, wisdom: `⏳ logged ${newest.cmd} (id=${newest.id})`, confidence: { level: "high" } };
  },
};

export const csqRecordDeltaTool: MnemeTool = {
  name: "mneme.consequence.record_delta",
  category: "lab",
  description:
    "⏳ CSQ — append the T+24h delta for a prior run id. Caller computes the delta (git diff stats, filesystem change counts, etc.) and pushes the summary.",
  whenToUse: "Daemon job: 24h after a run, snapshot the repo and post the delta.",
  triggers: ["consequence record delta", "log 24h delta"],
  inputSchema: {
    type: "object",
    properties: {
      runId: { type: "string" },
      repoStateAfter: { type: "string" },
      deltaSummary: { type: "object" },
    },
    required: ["runId", "repoStateAfter", "deltaSummary"],
  },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "Record 24h delta", args: { runId: "csq-abc", repoStateAfter: "cafebabe", deltaSummary: { commitsAdded: 2, commitsRemoved: 3 } }, expectedOutput: "{ ok }" }],
  pitfalls: ["Delta can only be recorded ONCE per run. Use mneme.consequence.list_recent to find runs awaiting delta."],
  handler: async (_rt, args) => {
    const core = await import("@mneme-ai/core");
    const ledger = await getCsq();
    const r = core.consequenceLedger.recordDelta({
      ledger,
      runId: String(args["runId"]),
      repoStateAfter: String(args["repoStateAfter"]),
      deltaSummary: (args["deltaSummary"] as Record<string, unknown>) ?? {},
    });
    if (r.ok) await setCsq(r.ledger);
    return { data: { ok: r.ok, reason: r.reason, totalRecords: r.ledger.records.length }, wisdom: r.ok ? `⏳ delta recorded for ${args["runId"]}` : `❌ ${r.reason}`, confidence: { level: "high" } };
  },
};

export const csqQueryTool: MnemeTool = {
  name: "mneme.consequence.query",
  category: "lab",
  description:
    "⏳ CSQ — aggregate deltas for a cmd: mean of numeric fields + top-5 histograms of non-numeric fields. The first 'what does my own CLI cause' query in any AI tool.",
  whenToUse: "Periodic causal-aware reflection: 'mneme verify on average causes X within 24h'.",
  triggers: ["consequence query", "what does cmd cause"],
  inputSchema: {
    type: "object",
    properties: { cmd: { type: "string" }, windowMs: { type: "number" } },
    required: ["cmd"],
  },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "What does mneme.verify tend to cause?", args: { cmd: "mneme.verify" }, expectedOutput: "{ totalRuns, runsWithDelta, averages, histograms }" }],
  pitfalls: ["Correlation, not causation. Window with at least 30 runs for any meaningful average."],
  handler: async (_rt, args) => {
    const core = await import("@mneme-ai/core");
    const ledger = await getCsq();
    const agg = core.consequenceLedger.queryConsequences({
      ledger,
      cmd: String(args["cmd"]),
      windowMs: args["windowMs"] as number | undefined,
    });
    return { data: agg, wisdom: core.consequenceLedger.formatConsequenceLine(agg), confidence: { level: "high" } };
  },
};

export const csqListRecentTool: MnemeTool = {
  name: "mneme.consequence.list_recent",
  category: "lab",
  description:
    "⏳ CSQ — list the N most recent run records (latest-per-id, newest first).",
  whenToUse: "Daemon work loop: 'which runs need a delta still?'",
  triggers: ["consequence list recent"],
  inputSchema: { type: "object", properties: { limit: { type: "number" } } },
  outputSchema: { type: "object" },
  examples: [{ userQuery: "Show recent runs", expectedOutput: "{ runs }" }],
  pitfalls: ["Returns latest record per id, not every chain entry."],
  handler: async (_rt, args) => {
    const core = await import("@mneme-ai/core");
    const ledger = await getCsq();
    const list = core.consequenceLedger.listRecentRuns(ledger, { limit: args["limit"] as number | undefined });
    return { data: { runs: list, count: list.length }, wisdom: `⏳ ${list.length} recent runs`, confidence: { level: "high" } };
  },
};

export const V1914_BONUS_TOOLS: MnemeTool[] = [
  dreamsEnqueueTool, dreamsResolveTool, dreamsDigestTool, dreamsPendingTool,
  chimeraClassifyTool, chimeraEmbedTool, chimeraDisagreeTool, chimeraListDomainsTool,
  csqRecordTool, csqRecordDeltaTool, csqQueryTool, csqListRecentTool,
];
