/**
 * Insights — applied storytelling, regret-mining, and prediction over git history.
 * 24 tools that surface narrative, friction, and risk patterns the user can act on.
 */

import { passthroughHandler } from "./_runtime.js";
import type { MnemeTool } from "./_types.js";

const passthrough = (
  name: string,
  description: string,
  triggers: string[],
  cli: string,
  argMap: (a: Record<string, unknown>) => string[] = () => [],
  inputSchema: MnemeTool["inputSchema"] = { type: "object", properties: {} },
  followUp: string[] = [],
  wisdom: (d: unknown) => string = () => "Result returned — summarize key fields for the user.",
): MnemeTool => ({
  name,
  category: "insights",
  description,
  triggers,
  inputSchema,
  handler: passthroughHandler(cli, argMap, { wisdom, followUp, confidence: "medium" }),
});

export const insightsTools: MnemeTool[] = [
  passthrough(
    "mneme.insights.ghost",
    "Half-finished features and stale TODOs haunting the repo — files born and forgotten. Use WHEN user asks: 'what is haunting my repo?', 'ghost code', 'half-finished features'.",
    ["ghost code", "half-finished features", "stale TODOs"],
    "ghost",
    (a) => (a["topN"] ? ["--top", String(a["topN"])] : []),
    { type: "object", properties: { topN: { type: "number" } } },
    ["mneme.insights.runaway", "mneme.insights.fossil"],
    (d) => `Found ${(d as { ghosts?: unknown[] })?.ghosts?.length ?? 0} ghost files. Each is born + forgotten — review for deletion.`,
  ),
  passthrough(
    "mneme.insights.regret",
    "Commits that were shipped and immediately fixed/reverted — instant-regret detector. Use WHEN user asks: 'what did we ship and regret?', 'recent reverts/hotfixes'.",
    ["shipped and regretted", "recent reverts"],
    "regret",
    (a) => (a["windowDays"] ? ["--window-days", String(a["windowDays"])] : []),
    { type: "object", properties: { windowDays: { type: "number" } } },
    ["mneme.insights.premortem", "mneme.audit.conscience"],
    (d) => `${(d as { regrets?: unknown[] })?.regrets?.length ?? 0} regrets found. Use to identify recurring failure patterns.`,
  ),
  passthrough(
    "mneme.insights.paradox",
    "Architectural flip-flops — A→B→A decisions over time. Use WHEN user asks: 'have we changed our minds repeatedly?', 'architectural paradoxes'.",
    ["architectural flip-flops", "decisions reversed"],
    "paradox",
    () => [],
    { type: "object", properties: {} },
    ["mneme.insights.decisions"],
  ),
  passthrough(
    "mneme.insights.oracle",
    "Predict next-window co-edits + author collisions on the same file. Use WHEN user asks: 'who will edit X next?', 'predict collisions'.",
    ["predict next edits", "author collisions"],
    "oracle",
    () => [],
    { type: "object", properties: {} },
  ),
  passthrough(
    "mneme.insights.premortem",
    "Predict regret risk for a proposed change, grounded in similar past attempts. Use WHEN user asks: 'will this be regretted?', 'risk of doing X', 'pre-mortem'.",
    ["pre-mortem of this change", "predict regret"],
    "premortem",
    (a) => (a["intent"] ? [String(a["intent"])] : []),
    { type: "object", properties: { intent: { type: "string", description: "Proposed change in plain English" } }, required: ["intent"] },
    ["mneme.audit.conscience", "mneme.memory.blast"],
    (d) => `Pre-mortem verdict in data.risk. Top historical analogues in data.precedents.`,
  ),
  passthrough(
    "mneme.insights.time_machine",
    "Tell a file's life as eras: birth → rewrite → firefight → plateau → evolution. Use WHEN user asks: 'tell me the story of this file', 'evolution of src/auth.ts'.",
    ["story of this file", "file evolution"],
    "time-machine",
    (a) => [String(a["file"])],
    { type: "object", properties: { file: { type: "string" } }, required: ["file"] },
    ["mneme.insights.story", "mneme.people.lineage"],
  ),
  passthrough(
    "mneme.insights.story",
    "Narrate the evolution of a topic across acts (with optional LLM polish). Use WHEN user asks: 'how did X evolve?', 'history of payments'.",
    ["how did X evolve", "story of feature"],
    "story",
    (a) => [String(a["topic"])],
    { type: "object", properties: { topic: { type: "string" } }, required: ["topic"] },
    ["mneme.insights.chronicle"],
  ),
  passthrough(
    "mneme.insights.decisions",
    "Auto-extract architectural decisions (ADRs) from commit history. Use WHEN user asks: 'list our ADRs', 'architectural decisions'.",
    ["ADR list", "architectural decisions"],
    "decisions",
    () => [],
    { type: "object", properties: {} },
    ["mneme.insights.story", "mneme.insights.paradox"],
  ),
  passthrough(
    "mneme.insights.mirror",
    "Onboarding dossier on a topic: 5 PRs, 3 people, 2 incidents. Use WHEN user asks: 'onboard me on payments', 'mirror for new hire on X'.",
    ["onboarding on payments", "mirror dossier"],
    "mirror",
    (a) => [String(a["topic"])],
    { type: "object", properties: { topic: { type: "string" } }, required: ["topic"] },
    ["mneme.people.who_knows", "mneme.insights.story"],
  ),
  passthrough(
    "mneme.insights.rumor",
    "Tribal phrases mentioned in commits/PRs but never documented. Use WHEN user asks: 'what slang does our team use?', 'undocumented terms'.",
    ["tribal slang", "undocumented terms"],
    "rumor",
    () => [],
    { type: "object", properties: {} },
  ),
  passthrough(
    "mneme.insights.fossil",
    "Files deleted from HEAD but still alive in git history. Use WHEN user asks: 'show deleted files', 'ghost code from history'.",
    ["deleted files in history", "fossils"],
    "fossil",
    () => [],
    { type: "object", properties: {} },
    ["mneme.insights.ghost"],
  ),
  passthrough(
    "mneme.insights.runaway",
    "Files growing silently across many commits — leak indicator. Use WHEN user asks: 'files growing silently', 'scope creep'.",
    ["files growing silently", "scope creep"],
    "runaway",
    () => [],
    { type: "object", properties: {} },
    ["mneme.insights.ghost"],
  ),
  passthrough(
    "mneme.insights.drift",
    "Topical drift — features → refactors → firefights → polish over time. Use WHEN user asks: 'what's our work pattern?', 'topical drift'.",
    ["topical drift", "work pattern over time"],
    "drift",
    () => [],
    { type: "object", properties: {} },
  ),
  passthrough(
    "mneme.insights.chronicle",
    "Auto-generate a chaptered narrative documentary of the whole repo. Use WHEN user asks: 'documentary of our repo', 'chronicle'.",
    ["documentary of repo", "chronicle"],
    "chronicle",
    () => [],
    { type: "object", properties: {} },
    ["mneme.insights.story"],
  ),
  passthrough(
    "mneme.insights.constellation",
    "Graph view: files as stars, authors as orbitals, commits as edges. Use WHEN user asks: 'visualize our repo', 'star map'.",
    ["constellation view", "visual repo map"],
    "constellation",
    () => [],
    { type: "object", properties: {} },
  ),
  passthrough(
    "mneme.insights.cluster",
    "Find topic islands — semantic clustering of commit messages. Use WHEN user asks: 'group commits by topic', 'topic clusters'.",
    ["topic clusters", "group commits"],
    "cluster",
    () => [],
    { type: "object", properties: {} },
  ),
  passthrough(
    "mneme.insights.network",
    "Author network — who collaborates with whom (co-edit + co-time + co-topic). Use WHEN user asks: 'collaboration graph', 'who works with whom'.",
    ["collaboration graph", "author network"],
    "network",
    () => [],
    { type: "object", properties: {} },
    ["mneme.people.telepathy", "mneme.people.nemesis"],
  ),
  passthrough(
    "mneme.insights.manage",
    "Engineering management dashboard — health, succession, skill matrix, trajectory. Use WHEN user asks: 'manager dashboard', 'team health for VP'.",
    ["manager dashboard", "team health summary"],
    "manage",
    () => [],
    { type: "object", properties: {} },
    ["mneme.people.nervous_system"],
  ),
  passthrough(
    "mneme.insights.export_bundle",
    "One bundle: DNA + drift + chronicle + oracle + constellation + clusters + network + manage + ghost. Use WHEN user asks: 'export everything', 'full repo bundle'.",
    ["export full bundle", "everything in one file"],
    "export-bundle",
    () => [],
    { type: "object", properties: {} },
  ),
  passthrough(
    "mneme.insights.dream",
    "Speculative ideas grounded in the codebase's own patterns. Use WHEN user asks: 'what should we build next?', 'speculative ideas'.",
    ["speculative ideas", "what should we build next"],
    "dream",
    () => [],
    { type: "object", properties: {} },
  ),
  passthrough(
    "mneme.insights.echo",
    "Find past incidents resembling the current one. Use WHEN user asks: 'has this happened before?', 'similar past incidents'.",
    ["has this happened before", "similar past incidents"],
    "echo",
    (a) => (a["query"] ? ["--query", String(a["query"])] : []),
    { type: "object", properties: { query: { type: "string" } } },
  ),
  passthrough(
    "mneme.insights.stack_trace",
    "Paste a stack trace, get historical context per frame. Use WHEN user asks: 'explain this stack trace', 'historical context for error'.",
    ["explain stack trace", "historical context per frame"],
    "stack-trace",
    () => [],
    { type: "object", properties: { from: { type: "string", description: "Path to error log" } } },
  ),
  passthrough(
    "mneme.insights.commit_coach",
    "Pre-commit AI partner — message, reviewers, scope, past warnings. Use WHEN user asks: 'review my staged commit', 'commit coach'.",
    ["pre-commit review", "commit coach"],
    "commit-coach",
    () => [],
    { type: "object", properties: {} },
  ),
  passthrough(
    "mneme.insights.crystal_ball",
    "Predict CI / follow-up failure probability before pushing. Use WHEN user asks: 'will CI fail?', 'crystal ball'.",
    ["will CI fail?", "predict push outcome"],
    "crystal-ball",
    () => [],
    { type: "object", properties: {} },
    ["mneme.audit.certify"],
  ),
];
