import { describe, it, expect } from "vitest";
import {
  COMMIT_SEP,
  DEFAULT_VENDOR_RULES,
  aiCommitCount,
  aiVendorBreakdown,
  detectAiVendor,
  parseCommitLog,
  parseShortstat,
  traceSession,
  type GitRunner,
} from "./trace.js";

describe("audit/trace — detectAiVendor", () => {
  it("detects Claude from Co-Authored-By trailer", () => {
    const r = detectAiVendor({
      message: "fix: bug\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
      authorEmail: "alice@example.com",
    });
    expect(r?.vendor).toBe("claude");
    expect(r?.confidence).toBeGreaterThan(0.9);
  });

  it("detects Claude from anthropic email even if message is silent", () => {
    const r = detectAiVendor({
      message: "fix typo",
      authorEmail: "noreply@anthropic.com",
    });
    expect(r?.vendor).toBe("claude");
  });

  it("detects Cursor from [Cursor] tag", () => {
    const r = detectAiVendor({
      message: "[Cursor] refactor handler",
      authorEmail: "dev@example.com",
    });
    expect(r?.vendor).toBe("cursor");
  });

  it("detects Codex from 'Generated by Codex' line", () => {
    const r = detectAiVendor({
      message: "Generated by Codex.\n\nadd retry logic",
      authorEmail: "dev@example.com",
    });
    expect(r?.vendor).toBe("codex");
  });

  it("detects Devin from message OR email", () => {
    expect(
      detectAiVendor({
        message: "(via devin.ai)",
        authorEmail: "dev@example.com",
      })?.vendor,
    ).toBe("devin");
    expect(
      detectAiVendor({
        message: "patch",
        authorEmail: "agent@devin.ai",
      })?.vendor,
    ).toBe("devin");
  });

  it("detects Sweep, Aider, Copilot", () => {
    expect(
      detectAiVendor({
        message: "Auto-PR by sweep.dev",
        authorEmail: "x@x.com",
      })?.vendor,
    ).toBe("sweep");
    expect(
      detectAiVendor({
        message: "via aider session",
        authorEmail: "x@x.com",
      })?.vendor,
    ).toBe("aider");
    expect(
      detectAiVendor({
        message: "fix\n\nCo-Authored-By: GitHub Copilot <copilot@github.com>",
        authorEmail: "x@x.com",
      })?.vendor,
    ).toBe("copilot");
  });

  it("returns undefined for human commits with no AI signal", () => {
    expect(
      detectAiVendor({
        message: "fix: a real bug",
        authorEmail: "alice@example.com",
      }),
    ).toBeUndefined();
  });

  it("DEFAULT_VENDOR_RULES is non-empty and covers the canonical vendors", () => {
    const vendors = new Set(DEFAULT_VENDOR_RULES.map((r) => r.vendor));
    for (const v of ["claude", "cursor", "codex", "devin", "sweep"]) {
      expect(vendors.has(v)).toBe(true);
    }
  });
});

describe("audit/trace — parseCommitLog", () => {
  it("parses a single commit block", () => {
    const block = `aaaaaaa\tAlice\talice@x.com\tfix: bug\n${COMMIT_SEP}\n`;
    const out = parseCommitLog(block);
    expect(out).toHaveLength(1);
    expect(out[0]!.hash).toBe("aaaaaaa");
    expect(out[0]!.author).toBe("Alice");
    expect(out[0]!.shortHash).toBe("aaaaaaa");
  });

  it("attaches AI detection per commit", () => {
    const raw =
      `aaa\tAlice\tnoreply@anthropic.com\tfix: stuff\n${COMMIT_SEP}\n` +
      `bbb\tBob\tbob@x.com\trefactor\n${COMMIT_SEP}\n`;
    const out = parseCommitLog(raw);
    expect(out).toHaveLength(2);
    expect(out[0]!.likelyAI?.vendor).toBe("claude");
    expect(out[1]!.likelyAI).toBeUndefined();
  });

  it("returns [] for empty input", () => {
    expect(parseCommitLog("")).toEqual([]);
    expect(parseCommitLog("   \n\n  ")).toEqual([]);
  });

  it("captures multi-line body", () => {
    const raw = `aaa\tAlice\talice@x.com\tfix: thing\nbody line 1\nbody line 2\n${COMMIT_SEP}\n`;
    const out = parseCommitLog(raw);
    expect(out[0]!.message).toContain("body line 1");
    expect(out[0]!.message).toContain("body line 2");
  });

  it("skips malformed header lines", () => {
    const raw = `not-enough-tabs\n${COMMIT_SEP}\naaa\tAlice\talice@x.com\tok\n${COMMIT_SEP}\n`;
    const out = parseCommitLog(raw);
    expect(out).toHaveLength(1);
    expect(out[0]!.hash).toBe("aaa");
  });
});

describe("audit/trace — parseShortstat", () => {
  it("parses standard --shortstat output", () => {
    const s = " 4 files changed, 32 insertions(+), 7 deletions(-)";
    expect(parseShortstat(s)).toEqual({ insertions: 32, deletions: 7 });
  });

  it("handles insertions-only", () => {
    const s = " 1 file changed, 5 insertions(+)";
    expect(parseShortstat(s)).toEqual({ insertions: 5, deletions: 0 });
  });

  it("returns zeros on empty input", () => {
    expect(parseShortstat("")).toEqual({ insertions: 0, deletions: 0 });
  });
});

describe("audit/trace — traceSession (mocked GitRunner)", () => {
  function makeRunner(responses: Record<string, string>): GitRunner {
    return {
      run(_cwd, args) {
        const key = args.join(" ");
        for (const [k, v] of Object.entries(responses)) {
          if (key.startsWith(k)) return v;
        }
        return "";
      },
    };
  }

  it("returns empty trace when HEAD == baseline", async () => {
    const runner = makeRunner({ "rev-parse HEAD": "abc\n" });
    const t = await traceSession("/repo", "abc", runner);
    expect(t.commits).toEqual([]);
    expect(t.insertions).toBe(0);
    expect(t.deletions).toBe(0);
    expect(t.fromHash).toBe("abc");
    expect(t.toHash).toBe("abc");
  });

  it("collects commits, files, and stats since baseline", async () => {
    const runner = makeRunner({
      "rev-parse HEAD": "newhead\n",
      "log abc..HEAD":
        `aaa\tAlice\tnoreply@anthropic.com\tfix\n${COMMIT_SEP}\n` +
        `bbb\tBob\tbob@x.com\trefactor\n${COMMIT_SEP}\n`,
      "diff --shortstat abc..HEAD": " 2 files changed, 10 insertions(+), 3 deletions(-)",
      "diff --name-only abc..HEAD": "src/a.ts\nsrc/b.ts\n",
    });
    const t = await traceSession("/repo", "abc", runner);
    expect(t.commits).toHaveLength(2);
    expect(t.commits[0]!.likelyAI?.vendor).toBe("claude");
    expect(t.filesChanged).toEqual(["src/a.ts", "src/b.ts"]);
    expect(t.insertions).toBe(10);
    expect(t.deletions).toBe(3);
    expect(t.fromHash).toBe("abc");
    expect(t.toHash).toBe("newhead");
  });

  it("dedupes file paths across commits", async () => {
    const runner = makeRunner({
      "rev-parse HEAD": "newhead\n",
      "log abc..HEAD": `aaa\tA\ta@x.com\tedit\n${COMMIT_SEP}\n`,
      "diff --shortstat abc..HEAD": "",
      "diff --name-only abc..HEAD": "src/a.ts\nsrc/a.ts\nsrc/b.ts\n",
    });
    const t = await traceSession("/repo", "abc", runner);
    expect(t.filesChanged).toEqual(["src/a.ts", "src/b.ts"]);
  });
});

describe("audit/trace — aggregations", () => {
  it("aiCommitCount + aiVendorBreakdown work together", () => {
    const trace = {
      fromHash: "x",
      toHash: "y",
      commits: [
        { hash: "1", shortHash: "1", author: "A", authorEmail: "a", message: "m", likelyAI: { vendor: "claude", confidence: 0.95 } },
        { hash: "2", shortHash: "2", author: "B", authorEmail: "b", message: "m", likelyAI: { vendor: "claude", confidence: 0.95 } },
        { hash: "3", shortHash: "3", author: "C", authorEmail: "c", message: "m", likelyAI: { vendor: "cursor", confidence: 0.9 } },
        { hash: "4", shortHash: "4", author: "D", authorEmail: "d", message: "m" },
      ],
      filesChanged: [],
      insertions: 0,
      deletions: 0,
    };
    expect(aiCommitCount(trace)).toBe(3);
    const b = aiVendorBreakdown(trace);
    expect(b[0]).toEqual({ vendor: "claude", count: 2 });
    expect(b[1]).toEqual({ vendor: "cursor", count: 1 });
  });

  it("aiVendorBreakdown returns [] when no AI commits", () => {
    expect(
      aiVendorBreakdown({
        fromHash: "x",
        toHash: "y",
        commits: [{ hash: "1", shortHash: "1", author: "A", authorEmail: "a", message: "m" }],
        filesChanged: [],
        insertions: 0,
        deletions: 0,
      }),
    ).toEqual([]);
  });
});
